objects/Additional_Domain__c.object
<CustomObject>
    <description>Used to hold additional domains for account email matching</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Additional_Domains</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Additional Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country_ISO_Map__c.object
<CustomObject>
    <description>JIRA SSF-62: this object maps full country names to the ISO 3166-1 alpha-2 (two letter) codes and alpha-3 (three letter) codes for the country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/DealRegistration__c.object
<CustomObject>
    <label>Deal Registration</label>
    <nameField>
        <label>DealRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Additional_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Additional_Domain__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal Registration</label>
        <referenceTo>DealRegistration__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                    <default>true</default>
                    <label>Business User</label>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>Partner</businessProcess>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi/classes/dealRegPageCompTest.cls
@isTest
private class dealRegPageCompTest {

  /**
    * Method to submit lead for conversion and check deal registration number update
    */
    public static  testMethod  void submitApprovalOfLeadConvertFailed() {
        List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        Account accObj = new Account(Name='test Account',BillingCountry='US',BillingState='NY',BillingPostalCode='10005');
        insert accObj;

        Additional_Domain__c domainObj = new Additional_Domain__c(Name='test domain',Account__c = accObj.ID);
        insert domainObj;


        Lead lead = new Lead(LastName='US',
                             FirstName='Convert',
                             Email='us.convert@storagecraft.com',
                             Company='Lead Convert Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Deal Registration',
                             Additional_Domain__c = domainObj.ID,
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:'Partner' LIMIT 1]
                             );
        insert lead;

        DealRegistration__c getInsertedDeal = [Select ID from DealRegistration__c];

        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(getInsertedDeal);
        dealRegPageCompClass controller = new dealRegPageCompClass(sc);
        controller.approveDR();
        controller.submitApproval();
        controller.cancel();
        System.Test.stopTest();
    }

    public static  testMethod  void submitApprovalOfDeal() {
        List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        Account accObj = new Account(Name='test Account',BillingCountry='US',BillingState='NY',BillingPostalCode='10005');
        insert accObj;

        Additional_Domain__c domainObj = new Additional_Domain__c(Name='test domain',Account__c = accObj.ID);
        insert domainObj;

        Lead lead = new Lead(LastName='US',
                             FirstName='Convert',
                             Email='us.convert@storagecraft.com',
                             Company='Lead Convert Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Deal Registration',
                             Additional_Domain__c = domainObj.ID,
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:'Partner' LIMIT 1]
                             );
        insert lead;

        Lead lead1 = new Lead(LastName='US',
                             FirstName='test',
                             Email='us@storagecraft.com',
                             Company='Lead Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Other',
                             Additional_Domain__c = domainObj.ID,
                             UserType__c = 'Other',
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:'Partner' LIMIT 1]
                             );
        insert lead1;
        DealRegistration__c getInsertedDeal = [Select ID from DealRegistration__c];

        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(getInsertedDeal);
        dealRegPageCompClass controller = new dealRegPageCompClass(sc);
        controller.approveDR();
        controller.drl =lead1;
        controller.submitApproval();
        controller.cancel();
        List<LeadStatus> leadList = [SELECT Id,IsConverted , MasterLabel FROM LeadStatus ];
        System.Test.stopTest();
        System.assertEquals(true,leadList[0].IsConverted);
    }

 /**
   * Method to submit lead for conversion and check failed to fetch lead ,cover catch block
   */
    public static  testMethod  void submitApprovalOfDealFailedFetchLead() {
        List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');
        Lead lead = new Lead(LastName='US',
                             Email='us.convert@storagecraft.com',
                             Company='Lead Convert Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Deal Registration',
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:'Partner' LIMIT 1]
                             );
        insert lead;
        DealRegistration__c getInsertedDeal = [Select ID from DealRegistration__c];
        DealRegistration__c dealInstance = new DealRegistration__c(Name = 'test deal');
        insert dealInstance;

        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(dealInstance);
        dealRegPageCompClass controller = new dealRegPageCompClass(sc);
        controller.approveDR();
        System.Test.stopTest();

        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        System.assertEquals(true,pageMessages[0].getDetail().contains('error'));
    }

  /**
    * Method to submit lead for conversion and reject on approval asked
    */
    public static  testMethod  void submitRejectionOfDeal() {
        List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');
        Lead lead = new Lead(LastName='US',
                             FirstName='Convert',
                             Email='us.convert@storagecraft.com',
                             Company='Lead Convert Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Deal Registration',
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:'Partner' LIMIT 1]
                             );
        insert lead;
        DealRegistration__c getInsertedDeal = [Select ID from DealRegistration__c];

        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(getInsertedDeal);
        dealRegPageCompClass controller = new dealRegPageCompClass(sc);
        controller.rejectDR();
        controller.submitRejection();
        List<Lead> getInsertedDeal1 = [Select ID,Status from Lead];
        System.Test.stopTest();

        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        System.assertEquals(true,pageMessages[0].getDetail().contains('reject'));
        System.assertEquals('Rejected',getInsertedDeal1[0].Status);
    }

  /**
    * Method to submit lead for conversion and reject approval when asked and cover catch block
    */
    public static  testMethod  void rejectApprovalOfDealFailedFetchLead() {
        List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');
        Lead lead = new Lead(LastName='US',
                             Email='us.convert@storagecraft.com',
                             Company='Lead Convert Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Deal Registration',
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:'Partner' LIMIT 1]
                             );
        insert lead;
        DealRegistration__c getInsertedDeal = [Select ID from DealRegistration__c];
        DealRegistration__c dealInstance = new DealRegistration__c(Name = 'test deal');
        insert dealInstance;

        System.Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(dealInstance);
        dealRegPageCompClass controller = new dealRegPageCompClass(sc);
        controller.rejectDR();
        System.Test.stopTest();
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        System.assertEquals(true,pageMessages[0].getDetail().contains('error'));

    }
}