objects/Additional_Domain__c.object
<CustomObject>
    <description>Used to hold additional domains for account email matching</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Additional_Domains</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Additional Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/DealRegistration__c.object
<CustomObject>
    <fields>
        <fullName>EndUserOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>End User Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deal Registrations</relationshipLabel>
        <relationshipName>DealRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpirationDate__c</fullName>
        <defaultValue>today()+30</defaultValue>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QualifiedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DealRegistrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QualifiedDate__c</fullName>
        <label>Qualified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                    <default>true</default>
                    <label>Pending Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SystemStatus__c</fullName>
        <formula>if( 
ISBlank(Lead__c), 
&quot;nolead&quot;, 
if( 
Lead__r.IsConverted, 
if( 
ISBlank(EndUserOpportunity__c), 
&quot;noopp&quot;, 
if( 
EndUserOpportunity__r.IsClosed, 
if( 
EndUserOpportunity__r.IsWon, 
&quot;won&quot;, 
&quot;lost&quot; 
), 
&quot;working&quot; 
) 
), 
if( 
Lead__r.IsDisqualified__c, 
&quot;rejected&quot;, 
&quot;new&quot; 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>System Status</label>
        <type>Text</type>
    </fields>
    <label>Deal Registration</label>
    <nameField>
        <label>DealRegistration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Additional_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Additional_Domain__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealRegistration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal Registration</label>
        <referenceTo>DealRegistration__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DomainAccountID__c</fullName>
        <formula>Additional_Domain__r.Account__r.Id</formula>
        <label>DomainAccountID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi/classes/dealRegPageCompClass.cls
public class dealRegPageCompClass {

  public final dealregistration__c dealreg {get;set;}
  public  dealregistration__c dr {get;set;}
  public boolean approve {get;set;}
  public boolean reject {get;set;}
  public lead drl {get;set;}
  public opportunity dro {get;set;}

  public dealRegPageCompClass(ApexPages.StandardController controller) {
    this.dealreg = (dealregistration__c)controller.getRecord();
    fetchDealReg();
    if(dr.status__c != 'Pending Approval' && dr.status__c != 'Rejected'){
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'This Deal has been approved and is currently an opportunity'));
    }
    else if(dr.status__c == 'Rejected'){
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'This Deal has been rejected.'));
    }
    approve = false;
    reject = false;
  }
  public void approveDR(){
    fetchDealReg();
    if(dr.systemstatus__c == 'New'){
      try{
        drl = fetchlead();
        approve = true;
        confirmApprovalMessage();
      }
      catch(Exception leadqueryfailed){
        failedLeadQuery();
      }
    }
    else if(dr.systemstatus__c == 'Working'){
      try{
        dro = fetchOpp();
        approve = true;
        confirmApprovalMessage();
      }
      catch(Exception leadqueryfailed){
        failedOppQuery();
      }
    }
    else{
      somethingsAmiss();
    }
  }
  public void rejectDR(){
    try{
      drl = fetchlead();
      reject = true;
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Are you sure you want to reject this deal registration?'));
    }
    catch(Exception leadqueryfailed){
      failedLeadQuery();
    }
  }
  public void fetchDealReg(){
    dr = [select status__c,systemstatus__c,QualifiedBy__c,QualifiedDate__c,EndUserOpportunity__c,name from dealregistration__c where id = : dealreg.id];
  }
  public lead fetchLead(){
    return [select status,DomainAccountID__c,Company,Additional_Domain__r.Account__c,Additional_Domain__r.Account__r.Name from lead where dealregistration__c = : dr.id];
  }
  public opportunity fetchOpp(){
    return [select stagename,DealRegistration__c from opportunity where id = :dr.EndUserOpportunity__c];
  }
  public void failedLeadQuery(){
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'There is an error with the deal registration lead. Please contact your system administrator.'));
  }
  public void failedOppQuery(){
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'There is an error with the deal registration opportunity. Please contact your system administrator.'));
  }
  public void confirmApprovalMessage(){
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Are you sure you want to approve this deal registration?'));
  }
  public void somethingsAmiss(){
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Something went wrong. Please reload the page and try again. If you have seen this error more than once please contact your administrator.'));
  }
  public pagereference cancel(){
    PageReference ref = new PageReference('/apex/dealregpagecomp?id='+dr.id);
    ref.setredirect(true);
    return ref;
  }
  public pagereference submitApproval(){
    boolean success = false;
    if(dr.systemstatus__c == 'new'){
      success = convertDealReg();
    }
    else if(dr.systemstatus__c == 'working'){
      success = true;
    }
    else{
      somethingsAmiss();
    }
    if(success){
      string status = 'Working';
      setQualifier(status);
      PageReference ref = new PageReference('/apex/dealregpagecomp?id='+dr.id);
      ref.setredirect(true);
      return ref;
    }
    else{
      return null;
    }
  }
  public pagereference submitRejection(){
    drl.status = 'Rejected';
    update drl;
    string status = 'Rejected';
    setQualifier(status);
    PageReference ref = new PageReference('/apex/dealregpagecomp?id='+dr.id);
    ref.setredirect(true);
    return ref;
  }
  public void setQualifier(string status){
    dr.status__c = status;
    dr.QualifiedBy__c = UserInfo.getUserId();
    dr.QualifiedDate__c  = datetime.now();
    if(status == 'Working'){
      dr.ExpirationDate__c = date.today().adddays(60);
    }
    update dr;
  }
  public boolean convertDealReg(){
    List<Database.LeadConvert> leadsToConvert = new List<Database.LeadConvert>();
    LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
    Database.LeadConvert objLeadConvert = new Database.LeadConvert();
    //objLeadConvert.setDoNotCreateOpportunity(true);
    String convertedOppName = dr.name;
    objLeadConvert.setLeadId(drl.id);
    objLeadConvert.setConvertedStatus(convertStatus.MasterLabel);
    if(dr.EndUserOpportunity__c != null){
      objLeadConvert.setDoNotCreateOpportunity(true);
    }
    else{
      if(drl.DomainAccountID__c != null){
        objLeadConvert.setAccountId(drl.DomainAccountID__c);
      }
      if(drl.Additional_Domain__r.Account__r != null)
        convertedOppName = drl.Additional_Domain__r.Account__r.Name+' '+convertedOppName;
      else
        convertedOppName = drl.Company+' '+convertedOppName;
      objLeadConvert.setOpportunityName(convertedOppName);
    }
    leadsToConvert.add(objLeadConvert);
    List<Database.LeadConvertResult> leadConversionresult = convertLeads(leadsToConvert);
    if(leadConversionresult[0].isSuccess()){
      return true;
    }
    else{
      string errorMessage = 'Lead conversion failed due to error: '+(leadConversionresult[0].getErrors())[0].getMessage();
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,errorMessage));
      return false;
    }
  }
  public static List<Database.LeadConvertResult> convertLeads(List<Database.LeadConvert> leadsToConvert){
    List<Database.LeadConvertResult> leadConversionResult = Database.convertLead(leadsToConvert, False);
    for (Database.LeadConvertResult lcr : leadConversionResult){
      System.Debug('@@@@@@@@-------------'+lcr);
    }
    return leadConversionResult;
  }
}
/*
Have conversion process update deal reg details? Perhaps hide conversion button and only allow through approval?
Set dr status on won or lost
*/