objects/Country_ISO_Map__c.object
<CustomObject>
    <description>JIRA SSF-62: this object maps full country names to the ISO 3166-1 alpha-2 (two letter) codes and alpha-3 (three letter) codes for the country</description>
    <fields>
        <fullName>countryCode__c</fullName>
        <description>This is the country calling code for IDD</description>
        <inlineHelpText>This is the country calling code for IDD (include &apos;+&apos; at the beginning)</inlineHelpText>
        <label>Country Calling Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postalCodeExample__c</fullName>
        <description>JIRA SSF-65</description>
        <inlineHelpText>Specify an example of what the ZIP/Postal code should look like</inlineHelpText>
        <label>ZIP/Postal code example</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postalCodeRegex__c</fullName>
        <description>JIRA SSF-65: regex formula to validate the ZIP/Postal codes for the country (if applicable)</description>
        <inlineHelpText>Regular expression (regex) formula to validate the ZIP/Postal codes for the country (if applicable)</inlineHelpText>
        <label>ZIP/Postal code regex</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>telephoneFormats__c</fullName>
        <description>JSON document describing all possible telephone number formats</description>
        <inlineHelpText>This contains possible telephone number (landline and mobile/cell) formats as a JSON string</inlineHelpText>
        <label>Telephone formats</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/triggerDisablement__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will control Trigger disablement at a global level (SSF-528). This requires that a Trigger conforms to the new Trigger framework (SSF-330).</description>
    <fields>
        <fullName>isDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the trigger is disabled or not</description>
        <label>Is disabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Disablement</label>
</CustomObject>

mdapi/classes/CountryIsoMapTriggerHandler.cls
/**
  \file         CountryIsoMapTriggerHandler.cls
  \brief        This class will implement a trigger handler for the Country_ISO_Map__c custom object
  \details      JIRA ticket(s): SSF-62, SSF-65
  \author       Matt Thompson-Moltzen
  \version      1.2
  \date         22 August 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1       2017-08-16  Matt Thompson-Moltzen   Validate individual deconstructor regex in telephone formats (SSF-501).
  1.2       2017-08-22  Matt Thompson-Moltzen   Added disabled trigger functionality (SSF-528).
*/
public with sharing class CountryIsoMapTriggerHandler implements TriggerSingularInterface
{
  //
  // variables
  //
  private static Boolean isDisabled = false;


  public static void disableTrigger()
  {
    isDisabled = true;
  }

  public static void enableTrigger()
  {
    isDisabled = false;
  }

	//
  // constructor
  //
  public CountryIsoMapTriggerHandler()
  {
  }

  public Boolean isDisabled()
  {
    triggerDisablement__c td = triggerDisablement__c.getInstance('countryIsoMapTrigger');

    if      (td == null)               { return isDisabled; }
    else if (td.isDisabled__c == true) { return true; }
    else                               { return isDisabled; }
  }

	//
 	// member functions/methods - define all methods from the interface even if not used
	//
  public void preBeforeOperations()
  {
  }

  public void beforeInsert(SObject newObject)
  {
  	Country_ISO_Map__c cim = (Country_ISO_Map__c)newObject;

      if (cim.postalCodeRegex__c == null) {
          cim.postalCodeExample__c = '';
      }
      else {
        Pattern p = null;

        try {
          p = Pattern.compile(cim.postalCodeRegex__c);
        }
        catch (Exception e) {
          cim.postalCodeRegex__c.addError(e.getMessage());
        }
      }

      if (cim.countryCode__c != null) {
        List<String> codes = cim.countryCode__c.split(',');

        for (String s : codes) {
          Matcher m = Pattern.compile('^\\+(\\d{1,3})(\\-\\d{1,5})?$').matcher(s);

          if (m.matches() == false) { cim.countryCode__c.addError('invalid format for the Country Calling Code: examples are +1 (US), +1-441 (Bermuda)'); }
        }
      }

      if (cim.telephoneFormats__c != null) {
        if (cim.countryCode__c == null) { cim.countryCode__c.addError('specify the Country Calling Code (include \'+\' at the beginning)'); }

        JsonTelephone jt = null;

        try {
          jt = JsonTelephone.parse(cim.telephoneFormats__c);
        }
        catch (Exception e) {
          cim.telephoneFormats__c.addError('invalid JSON document format: ' + e.getMessage());
        }

        if (jt != null) {
          Integer nFormats = jt.formats.size();
          Integer i = 0;

          for (i = 0; i < nFormats; i++) {
            Pattern p = null;

            try {
              p = Pattern.compile(jt.formats[i].deconstructor);
            }
            catch (Exception e) {
              cim.telephoneFormats__c.addError('invalid deconstructor regex: ' + e.getMessage());
            }
          }
        }
      }
  	}

  	public void beforeUpdate(SObject oldObject, SObject newObject)
  	{
  		Country_ISO_Map__c cim = (Country_ISO_Map__c)newObject;

      if (cim.postalCodeRegex__c == null) {
        cim.postalCodeExample__c = '';
      }
      else {
        Pattern p = null;

        try {
          p = Pattern.compile(cim.postalCodeRegex__c);
        }
        catch (Exception e) {
          cim.postalCodeRegex__c.addError(e.getMessage());
        }
      }

      if (cim.countryCode__c != null) {
        List<String> codes = cim.countryCode__c.split(',');

        for (String s : codes) {
          Matcher m = Pattern.compile('^\\+(\\d{1,3})(\\-\\d{1,5})?$').matcher(s);

          if (m.matches() == false) { cim.countryCode__c.addError('invalid format for the Country Calling Code: examples are +1 (US), +1-441 (Bermuda)'); }
        }
      }

      if (cim.telephoneFormats__c != null) {
        if (cim.countryCode__c == null) { cim.countryCode__c.addError('specify the Country Calling Code (include \'+\' at the beginning)'); }

        JsonTelephone jt = null;

        try {
          jt = JsonTelephone.parse(cim.telephoneFormats__c);
        }
        catch (Exception e) {
          cim.telephoneFormats__c.addError('invalid JSON document format: ' + e.getMessage());
        }

        if (jt != null) {
          Integer nFormats = jt.formats.size();
          Integer i = 0;

          for (i = 0; i < nFormats; i++) {
            Pattern p = null;

            try {
              p = Pattern.compile(jt.formats[i].deconstructor);
            }
            catch (Exception e) {
              cim.telephoneFormats__c.addError('invalid deconstructor regex: ' + e.getMessage());
            }
          }
        }
      }
  	}

  	public void beforeDelete(SObject oldObject)
  	{
  	}

  	public void preAfterOperations()
  	{
  	}

  	public void afterInsert(SObject newObject)
  	{
  	}

  	public void afterUpdate(SObject oldObject, SObject newObject)
  	{
  	}

  	public void afterDelete(SObject oldObject)
  	{
  	}

  	public void postOperations()
  	{
  	}

}