objects/Country_ISO_Map__c.object
<CustomObject>
    <description>JIRA SSF-62: this object maps full country names to the ISO 3166-1 alpha-2 (two letter) codes and alpha-3 (three letter) codes for the country</description>
    <fields>
        <fullName>alpha2Code__c</fullName>
        <description>JIRA SSF-62</description>
        <externalId>true</externalId>
        <label>Alpha-2 code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>alpha3Code__c</fullName>
        <description>JIRA SSF-62</description>
        <label>Alpha-3 code</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product_interested_in__c</fullName>
        <label>Product interested in</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>4312</fullName>
                </value>
                <value>
                    <fullName>5210</fullName>
                </value>
                <value>
                    <fullName>Both 4312 and 5210</fullName>
                </value>
                <value>
                    <fullName>Exablox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>PacWest</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>South Asia</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Canada - East</fullName>
                </value>
                <value>
                    <fullName>Canada - West</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                    <default>true</default>
                    <label>Business User</label>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAR_Agreement_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the Lead accepted the VAR Agreement?</description>
        <label>VAR Agreement Accepted</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>Partner</businessProcess>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi/classes/LeadS2SHandlerTest.cls
@isTest
private class LeadS2SHandlerTest {
    static testMethod void InsertForExabloxLead() {
        System.Test.startTest();

        Lead objlead1 = createLeadUS('Business User', 'Partner', true, null,'Exablox');
        system.assertNotEquals(null,objlead1.ID);
        List<PartnerNetworkRecordConnection> leadcon = createConnection('Exablox',objlead1.Id);
        System.Test.stopTest();

        List<PartnerNetworkRecordConnection> chkLeadConList = [SELECT Id, Status, ConnectionId, LocalRecordId
                                                               FROM PartnerNetworkRecordConnection
                                                               WHERE LocalRecordId =: objlead1.Id limit 1];

        System.assertEquals(objlead1.Id, chkLeadConList[0].LocalRecordId);
        System.assertEquals('Invite', chkLeadConList[0].Status);
        System.assertNotEquals('Converted', objlead1.Status);
    }

    static testMethod void InsertForAUMigraLead() {
        System.Test.startTest();

        Lead objlead = createLeadUS('Business User', 'Partner', true, 'APAC','4312');
        system.assertNotEquals(null,objlead.ID);
        List<PartnerNetworkRecordConnection> leadcon1 = createConnection('StorageCraft Indo-Pacific',objlead.Id);
        System.Test.stopTest();

        List<PartnerNetworkRecordConnection> chkLeadConList = [SELECT Id, Status, ConnectionId, LocalRecordId
                                                            FROM PartnerNetworkRecordConnection
                                                            WHERE LocalRecordId =: objlead.Id limit 1];
        System.assertEquals(objlead.Id, chkLeadConList[0].LocalRecordId);
        System.assertEquals('Invite', chkLeadConList[0].Status);
        System.assertNotEquals('Converted', objlead.Status);
    }

    private static Lead createLeadUS(string utype, string rtype, boolean accepted,String regionValue,String productInterestedValue) {

        List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        Country_ISO_Map__c countryObj = [SELECT Id, Name, alpha2Code__c, alpha3Code__c FROM Country_ISO_Map__c
                                          WHERE alpha2Code__c='AF' AND Id IN : lstCountry LIMIT 1];

        Lead lead = new Lead(LastName='US',
                             FirstName='Convert',
                             Email='us.convert@storagecraft.com',
                             Company='Lead Convert Test',
                             Status='Inquiry',
                             Country='US',
                             State='NY',
                             PostalCode='10005',
                             LeadSource = 'Web',
                             UserType__c=utype,
                             Region__c = regionValue,
                             Product_interested_in__c = productInterestedValue,
                             RecordType = [SELECT Id FROM RecordType WHERE SObjectType='Lead' AND Name=:rtype LIMIT 1],
                             VAR_Agreement_Accepted__c=accepted);
        insert lead;
        return lead;
    }

    private static List<PartnerNetworkRecordConnection> createConnection(String connectionName,Id keyLeadId){
        List<PartnerNetworkConnection> partnerNetConList =
          [SELECT Id, CreatedById FROM PartnerNetworkConnection WHERE connectionStatus = 'Accepted' AND connectionName = :connectionName];

        List<PartnerNetworkRecordConnection> LeadConnections =  new  List<PartnerNetworkRecordConnection>();
        if(partnerNetConList.size() > 0){
            for(PartnerNetworkConnection objPNC: partnerNetConList) {
              PartnerNetworkRecordConnection newConnection =
                              new PartnerNetworkRecordConnection(
                                  ConnectionId = objPNC.Id,
                                  LocalRecordId = keyLeadId,
                                  SendClosedTasks = false,
                                  SendOpenTasks = false,
                                  SendEmails = false );
              LeadConnections.add(newConnection);
            }
        }
        insert LeadConnections;
        return LeadConnections;
    }
}