mdapi/objects/Academy_Certificate__c.object
<CustomObject>
    <description>Controls data for certificates earned through the Academy</description>
    <fields>
        <fullName>Certified_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact which has been certified</description>
        <inlineHelpText>Who received the certification</inlineHelpText>
        <label>Certified Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Account related to the Certified Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Academy Certificate</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Academy Certificate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcademyCertificateManager.cls
public class AcademyCertificateManager {
    // Set the Academy Certificate's Account from the Contact
    public static void setAccount(List<Academy_Certificate__c> newCerts) { 
        List<Id> certIds = new List<Id>();
        
        for (Academy_Certificate__c ac : newCerts) {
            certIds.Add(ac.Certified_Contact__c);
        }
        
        List<Contact> contacts = [SELECT Id, AccountId FROM Contact WHERE Id IN :certIds];
        
        for (Academy_Certificate__c cert : newCerts) {
            for (Contact c : contacts) {
            	if (cert.Certified_Contact__c == c.Id) {                
                	cert.Contact_Account__c = c.AccountId;
                    break;
                }
            }
        }
    }

    // If the Contact's Account has changed, update any Academy Certificates
    public static void updateAccount(List<Contact> oldContacts, List<Contact> newContacts) {
        List<Id> contactIds = new List<Id>();
        
        for (Integer i = 0; i < newContacts.size(); i++) {
            if (newContacts[i].AccountId != oldContacts[i].AccountId) {
                contactIds.Add(newContacts[i].Id);
            }
        }
            
        if (contactIds.size() > 0) {
            List<Academy_Certificate__c> updateCerts = new List<Academy_Certificate__c>();
            List<Academy_Certificate__c> certs = 
                        [SELECT Id, Contact_Account__c, Certified_Contact__c FROM Academy_Certificate__c WHERE Certified_Contact__c IN :contactIds];
                                    
            for (Academy_Certificate__c ac : certs) {
                for (Contact c : newContacts) {
                    if (ac.Certified_Contact__c == c.Id) {
                    	ac.Contact_Account__c = c.AccountId;
                    	updateCerts.add(ac);
                        break;
                	}
                }
            }
            
            if (updateCerts.size() > 0) {
                update updateCerts;
            }
		}
    }
}