mdapi/objects/Academy_Certificate__c.object
<CustomObject>
    <description>Controls data for certificates earned through the Academy</description>
    <fields>
        <fullName>Certificate_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Was the certificate sent?</inlineHelpText>
        <label>Certificate Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certification__c</fullName>
        <inlineHelpText>Certification received by the Contact</inlineHelpText>
        <label>Certification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>StorageCraft_Certified_Engineer</fullName>
                    <label>StorageCraft Certified Engineer</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Master_Engineer</fullName>
                    <label>StorageCraft Certified Master Engineer</label>
                </value>
                <value>
                    <fullName>StorageCraft_Sales_Professional</fullName>
                    <label>StorageCraft Certified Sales Professional</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Engineer_Offsite_Recovery</fullName>
                    <label>StorageCraft Certified Engineer-Offsite Recovery</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Professional</fullName>
                    <label>StorageCraft Certified Professional</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Specialist</fullName>
                    <label>StorageCraft Certified Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certified_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact which has been certified</description>
        <inlineHelpText>Who received the certification</inlineHelpText>
        <label>Certified Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Account related to the Certified Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>When the certification ends, leave empty for never.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Did the Contact pass the test?</inlineHelpText>
        <label>Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification</description>
        <formula>IF(Passed__c, 
    IF(OR(Expiration_Date__c == null, Expiration_Date__c &lt; Today()), 
        &apos;Expired&apos;, 
        IF (OR(TEXT(Certified_Contact__r.Status__c) == &apos;Left the company&apos;, 
               TEXT(Certified_Contact__r.Status__c) == &apos;Inactive&apos;), 
            &apos;Inactive&apos;, 
            &apos;Certified&apos;)), 
    &apos;Not Certified&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Academy Certificate</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Academy Certificate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Account.object
<CustomObject>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>High_Potential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Account to be treated as Gold/Platinum for assignment?</inlineHelpText>
        <label>High Potential</label>
        <type>Checkbox</type>
    </fields>

mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/StcZone__c.object
<CustomObject>
    <description>Object to hold Global Region, Region, Territory</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this StcZone active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_Accounts_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who gets assigned new Accounts for the Territory</inlineHelpText>
        <label>Assign Accounts To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StcZones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who gets assigned new Leads for the Territory</inlineHelpText>
        <label>Assign Leads To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StcZones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Controlling_Office__c</fullName>
        <label>Controlling Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cork, IE</fullName>
                </value>
                <value>
                    <fullName>Draper, Utah  US</fullName>
                </value>
                <value>
                    <fullName>Sydney, NSW AU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
    <label>StcZone</label>
    <nameField>
        <label>StcZone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StcZones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/StcZoneRule__c.object
<CustomObject>
    <fields>
        <fullName>Account_User_Types__c</fullName>
        <inlineHelpText>When processing an Account, which User Types apply.  Leave blank to allow any.</inlineHelpText>
        <label>Account User Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Should this Rule be applied</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Countries__c</fullName>
        <inlineHelpText>Comma separated list of countries</inlineHelpText>
        <label>Countries</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>High_Potential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Account for High Potential, Gold or Platinum only?</inlineHelpText>
        <label>High Potential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_User_Types__c</fullName>
        <inlineHelpText>Select the User Types which apply to this Rule when processing a Lead.  Leave empty if any User Type is allowed.</inlineHelpText>
        <label>Lead User Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>1000</defaultValue>
        <inlineHelpText>Order in which this Rule is applied</inlineHelpText>
        <label>Order</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postal_Codes__c</fullName>
        <inlineHelpText>Commas separated list of Postal Codes or single Function</inlineHelpText>
        <label>Postal Codes</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <inlineHelpText>Comma separated list of states</inlineHelpText>
        <label>States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StcZone__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>StcZone</label>
        <referenceTo>StcZone__c</referenceTo>
        <relationshipLabel>StcZoneRules</relationshipLabel>
        <relationshipName>StcZoneRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Works_On__c</fullName>
        <defaultValue>&quot;Both Leads and Accounts&quot;</defaultValue>
        <inlineHelpText>Does this rule apply to leads, accounts or both?</inlineHelpText>
        <label>Works On</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Both Leads and Accounts</fullName>
                </value>
                <value>
                    <fullName>Accounts Only</fullName>
                </value>
                <value>
                    <fullName>Leads Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>StcZoneRule</label>
    <nameField>
        <label>StcZoneRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StcZoneRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/globalValueSets/Global_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <masterLabel>Global Region</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US North</fullName>
    </customValue>
    <customValue>
        <fullName>US South</fullName>
    </customValue>
    <customValue>
        <fullName>US West</fullName>
    </customValue>
    <customValue>
        <fullName>Australia / New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/globalValueSets/Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Big Apple</fullName>
    </customValue>
    <customValue>
        <fullName>Northern California</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>Great Lakes</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>New England</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Atlantic</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>South Texas</fullName>
    </customValue>
    <customValue>
        <fullName>Los Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>Maui to Maine - West</fullName>
    </customValue>
    <customValue>
        <fullName>North Texas</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific Northwest</fullName>
    </customValue>
    <customValue>
        <fullName>Rocky Mountain</fullName>
    </customValue>
    <customValue>
        <fullName>Southern California</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Emerging Markets</fullName>
    </customValue>
    <customValue>
        <fullName>New South Wales North</fullName>
    </customValue>
    <customValue>
        <fullName>New South Wales South</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland, WA, NT</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria, Tasmania, SA</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>North Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA Emerging Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Austria / Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Benelux</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Territory</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/classes/AcademyCertificateLetterControllerTest.cls
/**
  \file         AcademyCertificateLetterControllerTest.apxc
  \brief        Test the Academy Certificate sending to a contact
  \details      Tests for AcademyCertificateLetterControllerTest.apxc.
  \author       Loch MacLeod
  \version      1.1
  \date         
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1       2017-10-15  Loch MacLeod            Add Sales Territory staff to email (SSF-85).
*/
@isTest
public class AcademyCertificateLetterControllerTest { 
    @testSetup static void setupTest() {        
        Stc.setTestSettings();
        
        Map<String, StcZone__c> zones = new Map<String, StcZone__c>();
        Profile p = [select Id from Profile where Name = 'System Administrator'];
        
        User user1 = new User(Username = 'john@test.zzz',
                         Email = 'john@test.zzz',
                         Alias = 'stczone1',
                         CommunityNickname = 'stczone1',
                         TimeZoneSidKey = 'GMT',
                         LocaleSidKey = 'en_US',
                         EmailEncodingKey = 'UTF-8',
                         LanguageLocaleKey = 'en_US',
                         FirstName = 'Test', 
                         LastName = 'User1',
                         ProfileId = p.Id);
        User user2 = new User(Username = 'jane@test.zzz',
                         Email = 'jane@test.zzz',
                         Alias = 'stczone2',
                         CommunityNickname = 'stczone2',
                         TimeZoneSidKey = 'GMT',
                         LocaleSidKey = 'en_US',
                         EmailEncodingKey = 'UTF-8',
                         LanguageLocaleKey = 'en_US',
                         FirstName = 'Test', 
                         LastName = 'User2',
                         ProfileId = p.Id);
        List<User> users = new List<User>();
        users.add(user1);
        users.add(user2);

        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert users;
        }
        
        zones.put('Big Apple',
                  new StcZone__c(Name = 'Big Apple',
                                 Region__c = 'US North',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Big Apple',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        zones.put('Unknown',
                  new StcZone__c(Name = 'Unknown',
                                 Region__c = 'US West',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Unknown',
                                 Assign_To__c = user2.Id,
                                 Assign_Accounts_To__c = user2.Id));
               insert zones.values();
        
        List<StcZoneRule__c> zoneRules = new List<StcZoneRule__c>();
         
        zoneRules.add(new StcZoneRule__c(Order__c = 100,
                                         Active__c = true,
                                         Name = 'US - Big Apple',
                                         StcZone__c = zones.get('Big Apple').Id,
                                         Countries__c = 'US',
                                         States__c = 'NY,NJ',
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 200,
                                         Active__c = true,
                                         Name = 'Remaining',
                                         StcZone__c = zones.get('Unknown').Id,
                                         Countries__c = null,
                                         States__c = null,
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                           
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        insert zoneRules;
    }
    
    static private Academy_Certificate__c createCertificate(String certification, Boolean passed, Date expiration) {                
        Account acct = new Account(Name = 'Test Account', CurrencyIsoCode = 'USD');
        insert acct;
        
        Contact con = new Contact(FirstName = 'TestFirst', LastName = 'TestLast', Status__c ='Active', AccountId = acct.id, CurrencyIsoCode = 'USD', Email = 'test@yahoo.com');
        insert con;
        
        Academy_Certificate__c cert = new Academy_Certificate__c(
            Certified_Contact__c = con.Id,
            Contact_Account__c = acct.Id,
            Passed__c = passed,
            Certification__c = certification,
            Expiration_Date__c = expiration);
        insert cert;
        
        return cert;
    }
    
    static testMethod void certficateSCME() {
        Academy_Certificate__c acSCME = createCertificate('StorageCraft_Certified_Master_Engineer', true, System.today() + 30);
        
        System.AssertEquals(acSCME.Certification__c, 'StorageCraft_Certified_Master_Engineer');
        
        Test.setCurrentPage(Page.AcademyCertificate_Letter);
        AcademyCertificateLetterController controllerSCME = new AcademyCertificateLetterController(new ApexPages.StandardController(acSCME));
        controllerSCME.getBackgroundImage();
        controllerSCME.getDateColor();
        controllerSCME.getNameLeft();
        controllerSCME.getDateTop();
        controllerSCME.getDateLeft();
        controllerSCME.getNameColor();
        controllerSCME.getNameTop();
            
        controllerSCME.sendEmail();            
    }
    
    static testMethod void certficateSCE() {
        Academy_Certificate__c acSCE = createCertificate('StorageCraft_Certified_Engineer', false, Date.today() + 2);
        
        System.AssertEquals(acSCE.Certification__c, 'StorageCraft_Certified_Engineer');
        
        Test.setCurrentPage(Page.AcademyCertificate_Letter);
        AcademyCertificateLetterController controllerSCE = new AcademyCertificateLetterController(new ApexPages.StandardController(acSCE));
        controllerSCE.getBackgroundImage();
        controllerSCE.getDateColor();
        controllerSCE.getNameLeft();
        controllerSCE.getDateTop();
        controllerSCE.getDateLeft();
        controllerSCE.getNameColor();
        controllerSCE.getNameTop();
    }
    
    static testMethod void certficateSSP() {
        Academy_Certificate__c acSSP = createCertificate('StorageCraft_Sales_Professional', false, Date.today());
        
        System.AssertEquals(acSSP.Certification__c, 'StorageCraft_Sales_Professional');
        
        Test.setCurrentPage(Page.AcademyCertificate_Letter);
        AcademyCertificateLetterController controllerSSP = new AcademyCertificateLetterController(new ApexPages.StandardController(acSSP));
        controllerSSP.getBackgroundImage();
        controllerSSP.getDateColor();
        controllerSSP.getNameLeft();
        controllerSSP.getDateTop();
        controllerSSP.getDateLeft();
        controllerSSP.getNameColor();
        controllerSSP.getNameTop();
    }
    
    static testMethod void certficateNull() {
        Academy_Certificate__c acSCS = createCertificate('StorageCraft_Certified_Specialist', true, date.today() +1);

        System.AssertEquals(acSCS.Certification__c, 'StorageCraft_Certified_Specialist');
        
        Test.setCurrentPage(Page.AcademyCertificate_Letter);
        AcademyCertificateLetterController controllerNull = new AcademyCertificateLetterController(new ApexPages.StandardController(acSCS));
        controllerNull.getBackgroundImage();
        controllerNull.getDateColor();
        controllerNull.getNameLeft();
        controllerNull.getDateTop();
        controllerNull.getDateLeft();
        controllerNull.getNameColor();
        controllerNull.getNameTop();
        
        try{
            controllerNull.sendEmail();    
        } catch(DMLException e){
            System.assert(e.getMessage().contains('Unavailable certification type: SCP' ), 'message=' + e.getMessage());
        }
    }
    
    static testMethod void certNotCertified() {
       Academy_Certificate__c ac = createCertificate('StorageCraft_Certified_Specialist', true, Date.today() - 2);
       
       Test.setCurrentPage(Page.AcademyCertificate_PDF);
       AcademyCertificateLetterController controller = new AcademyCertificateLetterController(new ApexPages.StandardController(ac));
       controller.sendEmail();
    }
    
    static testMethod void certifiedPDF() {        
        Academy_Certificate__c ac = createCertificate('StorageCraft_Certified_Master_Engineer', true, Date.today() + 2);
        
        Test.setCurrentPage(Page.AcademyCertificate_PDF);
        AcademyCertificateLetterController controller = new AcademyCertificateLetterController(new ApexPages.StandardController(ac));
        controller.sendEmail(); 
    }
            
    static testMethod void certifiedPDFSCME() {
        Academy_Certificate__c ac = createCertificate('StorageCraft_Certified_Master_Engineer', true, Date.today() +12);
        
        AcademyCertificateLetterController controller = new AcademyCertificateLetterController(new ApexPages.StandardController(ac));
        
        controller.sendEmail();
        Test.setCurrentPage(Page.AcademyCertificate_PDF);
        PageReference pageCertificate = Page.AcademyCertificate_PDF;
    }
    
    static testMethod void certifiedEng() {
        String abbreviation = 'SCME';
        String emailTemplate =  'AcademyCertificate SCME Email';
        String resourcenameLogos = 'AcademyCertificate_SCME_Logos';
        Boolean emailMe = TRUE;
        
        Account acct2 = new Account(Name = 'Test Account', CurrencyIsoCode = 'USD');
        insert acct2;
        
        Contact con2 = new Contact(FirstName = 'Test First', LastName = 'Test Last',Status__c ='Active',  AccountId = acct2.id, CurrencyIsoCode = 'USD', Email = 'test@yahoo.com');
        insert con2;
        
        Academy_Certificate__c ac3 = new Academy_Certificate__c();
        ac3.Contact_Account__c = acct2.Id;
        ac3.Certified_Contact__c = con2.Id;
        ac3.Passed__c = true;
        ac3.Certification__c = 'StorageCraft_Certified_Engineer';
        //insert ac2;
        ac3.Expiration_Date__c = date.today() +12;
        ac3.Certificate_Sent__c = true;
        ac3.Certificate_Sent_On__c = Date.today();
        insert ac3;
        
        Academy_Certificate__c acCert = [SELECT Status__c, Certification__c, Certified_Contact__c, 
                                         Certified_Contact__r.Name, Certified_Date__c, Certificate_Sent__c, Certificate_Sent_On__c from Academy_Certificate__c where id=:ac3.id];
        //Test.setCurrentPage(Page.AcademyCertificate_PDF);
        /*ApexPages.StandardController standardCon = new ApexPages.StandardController(ac3);
AcademyCertificateLetterController controller = new AcademyCertificateLetterController(standardCon);
delete ac3;
*/
        AcademyCertificateLetterController controller = new AcademyCertificateLetterController(new ApexPages.StandardController(acCert));
        
        controller.sendEmail();
        Test.setCurrentPage(Page.AcademyCertificate_PDF);
    }
    
    static testMethod void certifiedSalesPro() {
        String abbreviation = 'SCME';
        String emailTemplate =  'AcademyCertificate SCME Email';
        String resourcenameLogos = 'AcademyCertificate_SCME_Logos';
        Boolean emailMe = TRUE;
        
        Account acct2 = new Account(Name = 'Test Account', CurrencyIsoCode = 'USD');
        insert acct2;
        
        Contact con2 = new Contact(FirstName = 'Test First', LastName = 'Test Last',Status__c ='Active',  AccountId = acct2.id, CurrencyIsoCode = 'USD', Email = 'test@yahoo.com');
        insert con2;
        
        Academy_Certificate__c ac3 = new Academy_Certificate__c();
        ac3.Contact_Account__c = acct2.Id;
        ac3.Certified_Contact__c = con2.Id;
        ac3.Passed__c = true;
        ac3.Certification__c = 'StorageCraft_Sales_Professional';
        //insert ac2;
        ac3.Expiration_Date__c = date.today() +12;
        ac3.Certificate_Sent__c = true;
        ac3.Certificate_Sent_On__c = Date.today();
        insert ac3;
        
        Academy_Certificate__c acCert = [SELECT Status__c, Certification__c, Certified_Contact__c, 
                                         Certified_Contact__r.Name, Certified_Date__c, Certificate_Sent__c, Certificate_Sent_On__c from Academy_Certificate__c where id=:ac3.id];
        //Test.setCurrentPage(Page.AcademyCertificate_PDF);
        /*ApexPages.StandardController standardCon = new ApexPages.StandardController(ac3);
AcademyCertificateLetterController controller = new AcademyCertificateLetterController(standardCon);
delete ac3;
*/
        APexPages.StandardController con = New ApexPages.standardController ( acCert );
        AcademyCertificateLetterController controller = new AcademyCertificateLetterController(con);
        controller.sendEmail();
        abbreviation = null;
        Test.setCurrentPage(Page.AcademyCertificate_PDF);
    }
}