mdapi/objects/Academy_Certificate__c.object
<CustomObject>
    <description>Controls data for certificates earned through the Academy</description>
    <fields>
        <fullName>Certification__c</fullName>
        <inlineHelpText>Certification received by the Contact</inlineHelpText>
        <label>Certification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>StorageCraft_Certified_Engineer</fullName>
                    <label>StorageCraft Certified Engineer</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Master_Engineer</fullName>
                    <label>StorageCraft Certified Master Engineer</label>
                </value>
                <value>
                    <fullName>StorageCraft_Sales_Professional</fullName>
                    <label>StorageCraft Certified Sales Professional</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Engineer_Offsite_Recovery</fullName>
                    <label>StorageCraft Certified Engineer-Offsite Recovery</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Professional</fullName>
                    <label>StorageCraft Certified Professional</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Specialist</fullName>
                    <label>StorageCraft Certified Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certified_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact which has been certified</description>
        <inlineHelpText>Who received the certification</inlineHelpText>
        <label>Certified Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Account related to the Certified Contact</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Academy Certificate</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Academy Certificate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Level_Calculated__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <inlineHelpText>The calculated Partner Level determined by sales and certifications</inlineHelpText>
        <label>Partner Level - Calculated</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Level_Overwritten__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the Partner Level overwriting the calculated Partner Level?</inlineHelpText>
        <label>Partner Level Overwritten?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Level__c</fullName>
        <description>Imported from Workbench</description>
        <label>Partner Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/classes/AcademyCertificateManagerTest.cls
@isTest
private class AcademyCertificateManagerTest {       
    static TestMethod void test_trigger1() {        
        Account testAccount = new Account(
            Name = 'Account Trigger Testing',
            Type = 'Account',
            Partner_Level__c = 'None', 
            Partner_Level_Calculated__c = 'None',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'UT',
            BillingCountry = 'US',
            BillingPostalCode = '84117'
        );
        
        insert testAccount;
        
        System.debug('Account Id: ' + testAccount.id);
        
        Contact testContact = new Contact(FirstName = 'Test', 
                                          LastName = 'Dude',
                                          MailingState = 'UT',
                                          MailingCountry = 'US',
                                          MailingPostalCode = '84117',
                                          AccountId = testAccount.Id
                                         );
        insert testContact;
        
        System.debug('Test Contact: ' + testContact);
        
        Academy_Certificate__c cert = new Academy_Certificate__c( 
                                              Certified_Contact__c = testContact.Id,
                                              Certification__c = 'StorageCraft_Certified_Engineer'
                                         );
        insert cert;
                
        cert = [SELECT Id, Contact_Account__c FROM Academy_Certificate__c WHERE Id = :cert.Id];
        
        System.assert(cert.Contact_Account__c == testContact.AccountId);        
    }   
    
    static TestMethod void test_trigger2() {        
        Account testAccount = new Account(
            Name = 'Account Trigger Testing',
            Type = 'Account',
            Partner_Level__c = 'None', 
            Partner_Level_Calculated__c = 'None',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'UT',
            BillingCountry = 'US',
            BillingPostalCode = '84117'
        );
        
        insert testAccount;
        
        System.debug('Account Id: ' + testAccount.id);
        
        Contact testContact = new Contact(FirstName = 'Test', 
                                          LastName = 'Dude',
                                          MailingState = 'UT',
                                          MailingCountry = 'US',
                                          MailingPostalCode = '84117',
                                          AccountId = testAccount.Id
                                         );
        insert testContact;
        
        System.debug('Test Contact: ' + testContact);       
        
        Academy_Certificate__c cert = new Academy_Certificate__c( 
                                              Certified_Contact__c = testContact.Id,
                                              Certification__c = 'StorageCraft_Certified_Engineer'
                                         );
        insert cert;
         
        Account newAccount = new Account(
                                      Name = 'Account Trigger Test 2', 
                                      Type = 'Account', 
                                      Partner_Level__c = 'None', 
                                      Partner_Level_Calculated__c = 'None',
                                      Partner_Level_Overwritten__c = false,
                                      BillingCity = 'New Haven',
                                      BillingState = 'CT',
                                      BillingCountry = 'US',
                                      BillingPostalCode = '02581'
                                  );
        insert newAccount;
        
        System.debug('newAccount Id: ' + newAccount.Id);
        
        testContact.AccountId = newAccount.Id;
        update testContact;
                
        cert = [SELECT Id, Contact_Account__c FROM Academy_Certificate__c WHERE Id = :cert.Id];
        
        System.debug(cert.Id + ' cert Account Id: ' + cert.Contact_Account__c);
        
        System.assert(cert.Contact_Account__c == newAccount.Id);        
    }    
}