mdapi/objects/Academy_Certificate__c.object
<CustomObject>
    <description>Controls data for certificates earned through the Academy</description>
    <fields>
        <fullName>Certificate_Sent_On__c</fullName>
        <inlineHelpText>Date when certificate was sent</inlineHelpText>
        <label>Certificate Sent On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Certificate_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Was the certificate sent?</inlineHelpText>
        <label>Certificate Sent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certification__c</fullName>
        <inlineHelpText>Certification received by the Contact</inlineHelpText>
        <label>Certification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>StorageCraft_Certified_Engineer</fullName>
                    <label>StorageCraft Certified Engineer</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Master_Engineer</fullName>
                    <label>StorageCraft Certified Master Engineer</label>
                </value>
                <value>
                    <fullName>StorageCraft_Sales_Professional</fullName>
                    <label>StorageCraft Certified Sales Professional</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Engineer_Offsite_Recovery</fullName>
                    <label>StorageCraft Certified Engineer-Offsite Recovery</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Professional</fullName>
                    <label>StorageCraft Certified Professional</label>
                </value>
                <value>
                    <fullName>StorageCraft_Certified_Specialist</fullName>
                    <label>StorageCraft Certified Specialist</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certified_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The contact which has been certified</description>
        <inlineHelpText>Who received the certification</inlineHelpText>
        <label>Certified Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Academy Certificates</relationshipLabel>
        <relationshipName>Academy_Certificates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certified_Date__c</fullName>
        <inlineHelpText>Date when considered Certified</inlineHelpText>
        <label>Certified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification</description>
        <formula>IF(Passed__c, 
    IF(OR(Expiration_Date__c == null, Expiration_Date__c &lt; Today()), 
        &apos;Expired&apos;, 
        IF (OR(TEXT(Certified_Contact__r.Status__c) == &apos;Left the company&apos;, 
               TEXT(Certified_Contact__r.Status__c) == &apos;Inactive&apos;), 
            &apos;Inactive&apos;, 
            &apos;Certified&apos;)), 
    &apos;Not Certified&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Academy Certificate</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Academy Certificate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>StcZone_Territory__c</fullName>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/StcZone__c.object
<CustomObject>
    <description>Object to hold Global Region, Region, Territory</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this StcZone active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_Accounts_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who gets assigned new Accounts for the Territory</inlineHelpText>
        <label>Assign Accounts To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StcZones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who gets assigned new Leads for the Territory</inlineHelpText>
        <label>Assign Leads To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StcZones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
    <label>StcZone</label>
    <nameField>
        <label>StcZone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StcZones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/globalValueSets/Territory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Big Apple</fullName>
    </customValue>
    <customValue>
        <fullName>Northern California</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>Central</fullName>
    </customValue>
    <customValue>
        <fullName>Great Lakes</fullName>
    </customValue>
    <customValue>
        <fullName>Midwest</fullName>
    </customValue>
    <customValue>
        <fullName>New England</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Mid-Atlantic</fullName>
    </customValue>
    <customValue>
        <fullName>Southeast</fullName>
    </customValue>
    <customValue>
        <fullName>South Texas</fullName>
    </customValue>
    <customValue>
        <fullName>Los Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>Maui to Maine - West</fullName>
    </customValue>
    <customValue>
        <fullName>North Texas</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific Northwest</fullName>
    </customValue>
    <customValue>
        <fullName>Rocky Mountain</fullName>
    </customValue>
    <customValue>
        <fullName>Southern California</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Emerging Markets</fullName>
    </customValue>
    <customValue>
        <fullName>New South Wales North</fullName>
    </customValue>
    <customValue>
        <fullName>New South Wales South</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Queensland, WA, NT</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria, Tasmania, SA</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>North Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>South East Asia</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA Emerging Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Austria / Switzerland</fullName>
    </customValue>
    <customValue>
        <fullName>Benelux</fullName>
    </customValue>
    <masterLabel>Territory</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/AcademyCertificateLetterController.cls
/**
  \file         AcademyCertificateLetterController.apxc
  \brief        Send the Academy Certificate to a contact
  \details      With the Visualforce Page Academy Certificate Letter, send the certificate
                information to the contact and other related Salesforce users.  The page
                allows selection of users.
  \author       Loch MacLeod
  \version      1.1
  \date         
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1       2017-10-15  Loch MacLeod            Add Sales Territory staff to email (SSF-85).
*/
public class AcademyCertificateLetterController { 
    private final Academy_Certificate__c certificate;
    private PageReference pg;
    
    public boolean emailContact {get; set;}
    public boolean emailMe {get; set;}
    public boolean emailAcademy {get; set;}
    public boolean emailOwner {get; set;}
    public boolean emailTerritory {get; set;}
    public String message {get; set;}
    public String accountName {get; set;}
    public String accountOwner {get; set;}
    public String accountOwnerEmail {get; set;}
    public String contactId {get; set;}
    public String contactName {get; set;}
    public String contactEmail {get; set;}
    public String territoryTeam {get; set;}
    
    private List<User> team = new List<User>();
       
    public AcademyCertificateLetterController(ApexPages.StandardController controller) {
       if (!Test.isRunningTest()) { 
        controller.addFields(new List<String> {
            'Status__c',
            'Certification__c', 
            'Certified_Contact__c', 
            'Certified_Contact__r', 
            'Certified_Contact__r.Name', 
            'Certified_Date__c', 
            'Certificate_Sent__c', 
            'Certificate_Sent_On__c'});
       } 
        certificate = (Academy_Certificate__c)controller.getRecord();
        
        pg = (PageReference)controller.view();
        
        emailContact = true;
        emailMe = true;
        emailAcademy = true;
        emailOwner = true;
        emailTerritory = true;
        message = '';
        
        contactId = certificate.Certified_Contact__c;
        Contact c = 
            [SELECT Id, Name, Email, Account.Name, Account.Owner.Name, Account.Owner.Email, Account.StcZone_Territory__c
             FROM Contact 
             WHERE Id = :contactId
             LIMIT 1];
        contactName = c.Name;
        contactEmail = c.Email;
        territoryTeam = '';
        
        if (String.isBlank(c.Account.Name)) {
            accountName = '';
            accountOwner = '';
            accountOwnerEmail = '';
        } 
        else {
            accountName = c.Account.Name;
            accountOwner = c.Account.Owner.Name;
            accountOwnerEmail = c.Account.Owner.Email;
        }
        
        if (!String.isBlank(c.Account.StcZone_Territory__c)) {
            List<StcZone__c> zones = 
                [SELECT Id, Assign_Accounts_To__c, Assign_To__c
                 FROM StcZone__c 
                 WHERE Active__c = true AND Territory__c = :c.Account.StcZone_Territory__c];
            
            if (zones.size() > 0) {
                Map<Id, Id> userIds = new Map<Id, Id>();
                
                for (StcZone__c z : zones) {
                    userIds.put(z.Assign_Accounts_To__c, z.Assign_Accounts_To__c);
                    userIds.put(z.Assign_To__c, z.Assign_To__c);
                }
                
                team = [SELECT Id, Name, Email FROM User WHERE Id IN :userIds.keySet()];
                String teamMembers = '';
                for (User u : team) {
                    teamMembers = teamMembers + u.Name + ', ';
                }
                
                territoryTeam = teamMembers.Left(teamMembers.length() - 2);
            }
        }
    }
        
    public PageReference sendEmail() {
        String error;
        
        try {
            if (certificate == null) {
                error = 'Invalid Cerification.  No email sent.';
            }
            else if (!'Certified'.Equals(certificate.Status__c)) {
                error = 'Status is ' + certificate.Status__c + '.  No email sent';
            }
            else {
                String abbreviation = null;
                String emailTemplate = null;
                String resourcenameLogos = null;
                PageReference pageCertificate = Page.AcademyCertificate_PDF; 
                                       
                if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
                    abbreviation = 'SCME';
                    emailTemplate = 'AcademyCertificate SCME Email';
                    resourcenameLogos = 'AcademyCertificate_SCME_Logos';            
                }        
                else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
                    abbreviation = 'SCE';
                    emailTemplate = 'AcademyCertificate SCE Email';
                    resourcenameLogos = 'AcademyCertificate_SCE_Logos';            
                }       
                else if ('StorageCraft_Sales_Professional'.Equals(certificate.Certification__c)) {
                    abbreviation = 'SSP';
                    emailTemplate = 'AcademyCertificate SSP Email';
                    resourcenameLogos = 'AcademyCertificate_SSP_Logos';
                }
               
                if (abbreviation == null) {
                    error = 'Unavailable certification type: ' + certificate.Certification__c;
                }  
                else {
                    Map<String, String> emailTo = new Map<String, String>();
                    Map<String, String> carbonCopy = new Map<String, String>();
                    
                    if (emailMe) {
                        carbonCopy.put(UserInfo.getUserEmail(), UserInfo.getUserEmail());
                    }
                    if (emailAcademy) {
                        carbonCopy.put('academy@storagecraft.com', 'academy@storagecraft.com');
                    }
                    if (emailOwner) {
                        carbonCopy.put(accountOwnerEmail, accountOwnerEmail);
                    }
                    if (emailTerritory) {
                        for (User u : team) {
                            carbonCopy.put(u.Email, u.Email);
                        }
                    }
                    
                    if (emailContact) {
                        emailTo.put(contactEmail, contactEmail);
                    }
                    else {
                        emailTo = carbonCopy;
                        carbonCopy = new Map<String, String>(); 
                    }
                    
                    if (emailTo.size() > 0 ) {                    
                        Id idTemplate = [SELECT Id, Name FROM EmailTemplate WHERE Name = :emailTemplate].Id;
                         
                        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
                        pageCertificate.getParameters().put('id', certificate.Id);  
                        Blob blobCertificate;
                        if (!Test.isRunningTest()){
                            blobCertificate = pageCertificate.getContent(); 
                        }
                        else{
                            blobCertificate=Blob.valueOf('Unit Test Attachment Body'); 
                        }
                            Messaging.EmailFileAttachment pdfCertificate = new Messaging.EmailFileAttachment();
                            pdfCertificate.setInline(false);
                            pdfCertificate.setContentType('application/pdf');
                            pdfCertificate.setFileName('StorageCraft_Certificate_' + abbreviation + '.pdf');
                            pdfCertificate.setBody( blobCertificate );
                            attachments.Add(pdfCertificate);
                        
                        if (!String.isBlank(resourcenameLogos)) {
                            Blob blogLogos = null;
                            StaticResource sr = [Select s.Name, s.Id, s.Body From StaticResource s where s.Name = :resourcenameLogos];    
                            blogLogos = (Blob) sr.Body;  
    
                            Messaging.EmailFileAttachment zipLogos = new Messaging.EmailFileAttachment();
                            zipLogos.setInline(false);
                            zipLogos.setContentType('application/zip');
                            zipLogos.setFileName('StorageCraft_Certificate_Logos_' + abbreviation + '.zip');
                            zipLogos.setBody( blogLogos );
                            attachments.Add(zipLogos);
                        }
                       
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        mail.setUseSignature(false);                                            
                        mail.setFileAttachments(attachments);
                        mail.setTargetObjectId(contactId);
                        mail.setTemplateID(idTemplate); 
                        mail.setToAddresses(emailTo.values());
                        if (carbonCopy.size() > 0 ) {
                            mail.setCcAddresses(carbonCopy.values());
                        }                   
                        OrgWideEmailAddress owea = (OrgWideEmailAddress) [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'Academy'];
                        if (owea != null) {
                            mail.setOrgWideEmailAddressId(owea.Id);
                        }
                        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                        
                        certificate.Certificate_Sent__c = true;
                        certificate.Certificate_Sent_On__c = Date.today();
                        update certificate;
                        
                        return pg;
                    }
                    else {
                       error = 'No receiving email.';
                    }
                }
            }
        } catch (Exception e) {
            error = e.getMessage();
        }
        
        message = 'Failed to Send.  ' +  error;

        return null;
    }

    
    public String getBackgroundImage() {
        string resourceName;
        
        if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
            resourceName = 'AcademyCertificate_SCME';
        }        
        else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
            resourceName = 'AcademyCertificate_SCE';
        }       
        else if ('StorageCraft_Sales_Professional'.Equals(certificate.Certification__c)) {
            resourceName = 'AcademyCertificate_SSP';
        }
        else {
            return '';
        }
                             
        List<StaticResource> resourceList = [
            SELECT Name, NamespacePrefix, SystemModStamp 
            FROM StaticResource 
            WHERE Name = :resourceName];
        
        if (resourceList.size() == 1) { 
           String namespace = resourceList[0].NamespacePrefix;        
           return '/resource/'        
              + resourceList[0].SystemModStamp.getTime() + '/'        
              + (namespace != null && namespace != '' ? namespace + '__' : '')        
              + resourceName;
        }
        
        return '';
    }
    
    public String getNameColor() {
        return '#E9622E';
    }
    
    public String getDateColor() {        
        if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
            return '#FFFFFF';
        }           
        else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
            return '#004463';
        }
                
        return '#004463';
    }
    
    public String getNameTop() {        
        if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
            return '340px';
        }          
        else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
            return '340px';
        } 
                
        return '340px';
    }
    
    public String getNameLeft() {        
        if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
            return '70px';
        }          
        else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
            return '70px';
        } 
                
        return '70px';
    }
    
    public String getDateTop() {        
        if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
            return '685px';
        }         
        else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
            return '670px';
        }         
        else if ('StorageCraft_Sales_Professional'.Equals(certificate.Certification__c)) {
            return '690px';
        } 
                
        return '670px';
    }
    
    public String getDateLeft() {        
        if ('StorageCraft_Certified_Master_Engineer'.Equals(certificate.Certification__c)) {
            return '660px';
        }         
        else if ('StorageCraft_Certified_Engineer'.Equals(certificate.Certification__c)) {
            return '660px';
        } 
                
        return '660px';
    }
}