mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/classes/AccountPrimaryContactTest.cls
@isTest
private class AccountPrimaryContactTest {   
    // Contact becomes "Inactive"
    @isTest static void testOne() {
        Account testAccount = new Account(
            Name = 'TestAccount',
        	User_Type__c = 'Both MSP and VAR',
            Type = 'Prospect',
        	BillingStreet = '123 Test Street',
        	BillingCity = 'Holladay',
        	BillingState =  'UT',
        	BillingCountry = 'US',
        	BillingPostalCode = '84117');
        system.debug('Account: ' + testAccount);      
        insert testAccount;

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            UserType__c = 'Both MSP and VAR',
            FirstName = 'Test',
            LastName = 'Test',
            Phone = '801 555-5555',
            Email = 'test@storagecraft.com',
        	MailingStreet = '123 Test Street',
        	MailingCity = 'Holladay',
        	MailingState =  'UT',
        	MailingCountry = 'US',
        	MailingPostalCode = '84117');       
        system.debug('Contact: ' + testContact);
        insert testContact;

        testAccount = [SELECT Id, Primary_Contact__c FROM Account WHERE Id = :testAccount.Id];
        System.assertEquals(testContact.Id, testAccount.Primary_Contact__c);

        testContact.Status__c = 'Inactive';
		update testContact;  

        testAccount = [SELECT Id, Primary_Contact__c FROM Account WHERE Id = :testAccount.Id];
        System.assertEquals(null, testAccount.Primary_Contact__c);
    } 
    
    // Contact switches Accounts
    @isTest static void testTwo() {
        Account testAccount1 = new Account(
            Name = 'TestAccount1',
        	User_Type__c = 'Both MSP and VAR',
            Type = 'Prospect',
        	BillingStreet = '123 Test Street',
        	BillingCity = 'Holladay',
        	BillingState =  'UT',
        	BillingCountry = 'US',
        	BillingPostalCode = '84117');
        system.debug('Account 1: ' + testAccount1);      
        insert testAccount1;
        
        Account testAccount2 = new Account(
            Name = 'TestAccount2',
        	User_Type__c = 'Both MSP and VAR',
            Type = 'Prospect',
        	BillingStreet = '123 Test Street',
        	BillingCity = 'Holladay',
        	BillingState =  'UT',
        	BillingCountry = 'US',
        	BillingPostalCode = '84117');
        system.debug('Account 2: ' + testAccount2);      
        insert testAccount2;

        Contact testContact = new Contact(
            AccountId = testAccount1.Id,
            UserType__c = 'Both MSP and VAR',
            FirstName = 'Test',
            LastName = 'Test',
            Phone = '801 555-5555',
            Email = 'test@storagecraft.com',
        	MailingStreet = '123 Test Street',
        	MailingCity = 'Holladay',
        	MailingState =  'UT',
        	MailingCountry = 'US',
        	MailingPostalCode = '84117');        
        system.debug('Contact: ' + testContact);
        insert testContact;

        testAccount1 = [SELECT Id, Primary_Contact__c FROM Account WHERE Id = :testAccount1.Id];
        System.assertEquals(testContact.Id, testAccount1.Primary_Contact__c);

        testContact.AccountId = testAccount2.Id;
		update testContact;  

        testAccount1 = [SELECT Id, Primary_Contact__c FROM Account WHERE Id = :testAccount1.Id];
        System.assertEquals(null, testAccount1.Primary_Contact__c);
    }
}