mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionTypesAsText__c</fullName>
        <description>This is a text version of the Multi-Picklist transactionTypes__c field that can be used in formulae. It is not intended to be displayed or updated directly.</description>
        <label>Transaction Types (text)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/objects/Agreement__c.object
<CustomObject>
    <description>Account accepted agreements.</description>
    <fields>
        <fullName>Acceptance_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date when the agreement was made</inlineHelpText>
        <label>Acceptance Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account related to this agreement</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the Agreement</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cash Only</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>What type of agreement is this?</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>Master MSP</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <label>Country Partner</label>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/classes/Agreements.cls
/**
  \file
  \brief        This class will implement Agreements related functions
  \details      JIRA ticket(s): SSF-115
  \author       Matt Thompson-Moltzen
  \version      1.6
  \date         27 September 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.5       2017-08-30  Matt Thompson-Moltzen   Changed references to User_Type__c to transactionTypesAsText__c (SSF-458).
  1.6       2017-09-27  Matt Thompson-Moltzen   Removed references to transactionTypesAsText__c as Portal does not use User Type (SSF-458).
*/

public class Agreements
{
  //
  // variables
  //
  private String toAddress;
  private List<OrgWideEmailAddress> owea;
  private URL url;

  //
  // constructor
  //
  public Agreements()
  {
    if (Stc.isProductionInstance()) { toAddress = 'DL-OrderDesk@storagecraft.com'; }
    else                            { toAddress = 'matt.tm@storagecraft.com.au'; }

    owea = [SELECT Id, DisplayName, Address FROM OrgWideEmailAddress WHERE Address = 'crm@storagecraft.com'];
    url  = System.URL.getSalesforceBaseUrl();
  }

  //
  // member functions
  //
  public Boolean createCase(Agreement__c agreement)
  {
    Boolean hasFailures = false;

    Account account = [SELECT Name, BillingCountry, transactionTypesAsText__c FROM Account WHERE (Id = :agreement.Account__c)];
    Group   queue   = [SELECT Id, DeveloperName FROM Group WHERE (Type = 'Queue' AND DeveloperName = 'OrderDesk')];

    System.assert(account != null, 'Agreements::createCase(): unable to retrieve specified Account object details for: ' + agreement.Account__c);
    System.assert(queue != null, 'Agreements::createCase(): unable to retrieve specified Queue object details for: ' + 'OrderDesk');

    String body = agreement.Type__c + ' agreement ' + agreement.Name + ' for ' + account.Name + ' awaiting review and setup.\r\n\r\n';

    body += 'Status:          ' + agreement.Status__c + '\r\n';
    body += 'Acceptance Date: ' + agreement.Acceptance_Date__c.format() + '\r\n\r\n';

    body += 'Link: ' + url.toExternalForm() + '/' +  + agreement.Id + '\r\n\r\n';

    List <Case> cases = new List<Case>();

    Case c = new Case();

    c.OwnerId             = queue.Id;

    c.AccountId           = agreement.Account__c;

    if (account.BillingCountry != null) {
      Addresses addrs = new Addresses();

      c.Country__c = addrs.getCountryName(account.BillingCountry);
    }

    //
    // Since Transaction Types on Account is a Multi-Picklist, only the last value will be set
    //
//    List<String> typs = account.transactionTypesAsText__c.split(';');
//
//    for (String t : typs) {
//      c.Select_User_Type__c = t;
//    }

    c.Origin              = 'Customer Setup';
    c.Status              = 'New';
    c.Priority            = 'Medium';
    c.Type                = 'Order Entry';
    c.Subject             = agreement.Type__c + ' agreement ' + agreement.Name + ' awaiting review';
    c.Description         = body;

    cases.add(c);

    try {
      insert cases;
    }
    catch (DMLException e) {
      System.debug(LoggingLevel.ERROR, 'Agreements::createCase() exception: ' + e.getMessage());
    }

    return (hasFailures) ? false : true;
  }

  public Boolean sendEmail(Agreement__c agreement)
  {
    Boolean hasFailures = false;

    Account account = [SELECT Name FROM Account WHERE (Id = :agreement.Account__c)];

    List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();

    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();

    List<String> toAddresses = new List<String>();

    toAddresses.add(toAddress);

    String subject = 'ACTION: ' + agreement.Type__c + ' agreement ' + agreement.Name + ' awaiting review';
    String body    = agreement.Type__c + ' agreement ' + agreement.Name + ' for ' + account.Name + ' awaiting review and setup.\r\n\r\n';

    body += 'Status:          ' + agreement.Status__c + '\r\n';
    body += 'Acceptance Date: ' + agreement.Acceptance_Date__c.format() + '\r\n\r\n';

    body += 'Link: ' + url.toExternalForm() + '/' +  + agreement.Id + '\r\n\r\n';

    if (owea.size() > 0) { message.setOrgWideEmailAddressId(owea.get(0).Id); }

    message.setToAddresses(toAddresses);
    message.setSubject(subject);
    message.setPlainTextBody(body);

    messages.add(message);

    if (messages.size() > 0) {
      List<Messaging.SendEmailResult> results = new List<Messaging.SendEmailResult>();

      try {
        results = Messaging.sendEmail(messages);
      }
      catch (Exception e) {
        System.debug(LoggingLevel.ERROR, 'Agreements::sendEmail() exception: ' + e.getMessage());

        return false;
      }

      Integer i = 0;

      for (i = 0; i < results.size(); i++) {
        if (results[i].isSuccess() == false) {
          hasFailures = true;
          System.debug(LoggingLevel.ERROR, 'Agreements::sendEmail() failed: ' + results[i].errors[0].message);
        }
      }
    }

    return (hasFailures) ? false : true;
  }

}