mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Level_Calculated__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <inlineHelpText>The calculated Partner Level determined by sales and certifications</inlineHelpText>
        <label>Partner Level - Calculated</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Level_Overwritten__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the Partner Level overwriting the calculated Partner Level?</inlineHelpText>
        <label>Partner Level Overwritten?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Level__c</fullName>
        <description>Imported from Workbench</description>
        <label>Partner Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/classes/PartnerLevelManagerTest.cls
@isTest
public class PartnerLevelManagerTest {
/** Replaced by FLOW
    static TestMethod void test_trigger1() {
        System.debug('TEST 1:  Override Gold to Silver');
        
        test.startTest();
        
        account acct = new account(Name = 'Account Trigger Test 1',  
                                   Type = 'Account',
                                   User_Type__c = 'Both MSP and VAR',
                                   Partner_Level__c = 'Authorized', 
                                   Partner_Level_Calculated__c = 'Gold',
                                   BillingState = 'US',
                                   BillingCountry = 'CA',
                                   BillingPostalCode = '94132'
                                  );
        insert acct;        
        
        acct.Partner_Level_Calculated__c = 'Silver';
        acct.Partner_Level_Overwritten__c = true;
        
        update acct;
        
        acct = (Account) [SELECT Type, Partner_Level__c, Partner_Level_Calculated__c, Partner_Level_Overwritten__c FROM Account WHERE Id = :acct.Id];
        
        System.debug('Type: ' + acct.Type + '  Partner Level Calculated: ' + acct.Partner_Level_Calculated__c + '  Partner Level: ' + acct.Partner_Level__c + '  Partner_Level_Overwritten__c: ' + acct.Partner_Level_Overwritten__c);
        System.assertEquals('Authorized', acct.Partner_Level__c);
        System.assertEquals('Silver', acct.Partner_Level_Calculated__c);  
        
        test.stopTest();      
    }  
    
    static TestMethod void test_trigger2(){
        System.debug('TEST 2:  Change the calculated level');
        
        account acct = new account(Name = 'Account Trigger Test 2', 
                                   Type = 'Account',
                                   User_Type__c = 'Both MSP and VAR',
                                   Partner_Level_Calculated__c = 'Gold',
                                   Partner_Level_Overwritten__c = false,
                                   BillingState = 'US',
                                   BillingCountry = 'CA',
                                   BillingPostalCode = '94132');
        insert acct;
        
        test.startTest();
        
        acct.Partner_Level_Calculated__c = 'Silver';
                
        update acct;
        
        acct = (Account) [SELECT Type, Partner_Level__c, Partner_Level_Calculated__c, Partner_Level_Overwritten__c FROM Account WHERE Id = :acct.Id];
        
        System.debug('Type: ' + acct.Type + '  Partner Level Calculated: ' + acct.Partner_Level_Calculated__c + '  Partner Level: ' + acct.Partner_Level__c + '  Partner_Level_Overwritten__c: ' + acct.Partner_Level_Overwritten__c);
        System.assertEquals('Silver', acct.Partner_Level__c);
        System.assertEquals('Silver', acct.Partner_Level_Calculated__c);        
        
        test.stopTest();
    }    
    
    static TestMethod void test_trigger4(){
        System.debug('TEST 4:  Try to change Partner Level');
        
        account acct = new account(Name = 'Account Trigger Test 4',
                                   Type = 'Account',
                                   Partner_Level__c = 'Platinum', 
                                   Partner_Level_Calculated__c = 'Gold',
                                   Partner_Level_Overwritten__c = true,
                                   BillingState = 'US',
                                   BillingCountry = 'CA',
                                   BillingPostalCode = '94312');
        insert acct;
        
        acct.Partner_Level__c = 'Silver';
        
        update acct;
        
        acct = (Account) [SELECT Type, Partner_Level__c, Partner_Level_Calculated__c, Partner_Level_Overwritten__c FROM Account WHERE Id = :acct.Id];
                
        System.debug('Type: ' + acct.Type + '  Partner Level Calculated: ' + acct.Partner_Level_Calculated__c + '  Partner Level: ' + acct.Partner_Level__c + '  Partner_Level_Overwritten__c: ' + acct.Partner_Level_Overwritten__c);
        System.assertEquals('Silver', acct.Partner_Level__c);     
    } 
   
    static TestMethod void test_trigger5(){
        System.debug('TEST 5:  Just try setting the value on an Account');
        
        account acct = new account(Name = 'Account Trigger Test 5',
                                   User_Type__c = 'Both MSP and VAR',  
                                   Type = 'Account',
                                   Partner_Level_Overwritten__c = false,
                                   BillingState = 'US',
                                   BillingCountry = 'CA',
                                   BillingPostalCode = '19432');
        insert acct;
        
        acct.Partner_Level__c = 'Silver';
        
        update acct;
        
        acct = (Account) [SELECT Type, Partner_Level__c, Partner_Level_Calculated__c, Partner_Level_Overwritten__c FROM Account WHERE Id = :acct.Id];
        
        System.debug('Type: ' + acct.Type + '  Partner Level Calculated: ' + acct.Partner_Level_Calculated__c + '  Partner Level: ' + acct.Partner_Level__c + '  Partner_Level_Overwritten__c: ' + acct.Partner_Level_Overwritten__c);
        System.assertEquals('Authorized', acct.Partner_Level__c);
        System.assertEquals('Authorized', acct.Partner_Level_Calculated__c);      
    }
   
    static TestMethod void test_trigger6(){
        System.debug('TEST 6: Uncheck Overwrite');
        
        account acct = new account(Name = 'Account Trigger Test 5',
                                   User_Type__c = 'Both MSP and VAR',  
                                   Type = 'Account',
                                   Partner_Level__c = 'Gold',
                                   Partner_Level_Calculated__c = 'Silver',
                                   Partner_Level_Overwritten__c = true,
                                   BillingState = 'US',
                                   BillingCountry = 'CA',
                                   BillingPostalCode = '19432');
        insert acct;
        
        acct.Partner_Level_Overwritten__c = false;
        
        update acct;
        
        acct = (Account) [SELECT Type, Partner_Level__c, Partner_Level_Calculated__c, Partner_Level_Overwritten__c FROM Account WHERE Id = :acct.Id];
               
        System.debug('Type: ' + acct.Type + '  Partner Level Calculated: ' + acct.Partner_Level_Calculated__c + '  Partner Level: ' + acct.Partner_Level__c + '  Partner_Level_Overwritten__c: ' + acct.Partner_Level_Overwritten__c);
        System.assertEquals('Silver', acct.Partner_Level__c);
        System.assertEquals('Silver', acct.Partner_Level_Calculated__c);      
    }
**/
}