mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Level_Calculated__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <inlineHelpText>The calculated Partner Level determined by sales and certifications</inlineHelpText>
        <label>Partner Level - Calculated</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Level_Overwritten__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the Partner Level overwriting the calculated Partner Level?</inlineHelpText>
        <label>Partner Level Overwritten?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Level__c</fullName>
        <description>Imported from Workbench</description>
        <label>Partner Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assistance_Type__c</fullName>
        <label>Assistance Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Select_User_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Licensing Assistance</fullName>
                </value>
                <value>
                    <fullName>Technical Assistance</fullName>
                </value>
                <value>
                    <fullName>Sales Assistance</fullName>
                </value>
                <value>
                    <fullName>Product_Return</fullName>
                    <label>Product Return / RMA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Owner_On__c</fullName>
        <label>First Owner On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Select_User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <label>Country Partner</label>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/classes/PartnerCaseNotificationControllerTest.cls
@isTest
public class PartnerCaseNotificationControllerTest {
    @testSetup static void setupTest() {
    }
    
    static testMethod void test1() {
        account acct = new account(Name = 'Partner Case Test', 
                                   User_Type__c = 'Both MSP and VAR', 
                                   Partner_Level__c = 'Platinum',
                                   Partner_Level_Overwritten__c = True,
                                   Partner_Level_Calculated__c = 'Platinum'
                                   );
        insert acct;
   
        List<Case> cases = new List<Case>();
        cases.add(new Case(
          AccountId = acct.id,
          OwnerId = UserInfo.getUserId(),
          First_Owner_On__c = Datetime.now(),
          Select_User_Type__c = 'Both MSP and VAR',
          Assistance_Type__c = 'Technical Assistance'));
        Insert cases;
        
        PartnerCaseNotificationController enc = new PartnerCaseNotificationController();
        System.assertEquals(1, enc.eCases.size());
        System.assertEquals(0, enc.openPCases);
        System.assertEquals(false, enc.ownedByQueue.values()[0]);
        enc.caseToAssign = enc.eCases[0].Id;    
        enc.assignToMe();
    }
    
    
    static testMethod void test2() {
        account acct = new account(Name = 'Partner Case Test 2', 
                                   User_Type__c = 'Both MSP and VAR', 
                                   Partner_Level__c = 'Platinum',
                                   Partner_Level_Overwritten__c = True,
                                   Partner_Level_Calculated__c = 'Platinum'
                                   );
        insert acct;

        List<Case> cases = new List<Case>();
        Group g = [Select Id from Group where Name = 'US Partner'];
        cases.add(new Case(
          AccountId = acct.id,
          OwnerId = g.Id,
          Select_User_Type__c = 'Both MSP and VAR',
          Assistance_Type__c = 'Technical Assistance'));
        Insert cases;
        
        PartnerCaseNotificationController enc = new PartnerCaseNotificationController();
        System.assertEquals(1, enc.eCases.size());
        System.assertEquals(1, enc.openPCases);
        System.assertEquals(true, enc.ownedByQueue.values()[0]);
        enc.caseToAssign = enc.eCases[0].Id;    
        enc.assignToMe();
    }
}