mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionTypesAsText__c</fullName>
        <description>This is a text version of the Multi-Picklist transactionTypes__c field that can be used in formulae. It is not intended to be displayed or updated directly.</description>
        <label>Transaction Types (text)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionTypes__c</fullName>
        <inlineHelpText>Some of the Transaction Types will be automatically managed depending on any Agreements in place</inlineHelpText>
        <label>Transaction Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>transactionTypes</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Agreement__c.object
<CustomObject>
    <description>Account accepted agreements.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account related to this agreement</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the Agreement</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cash Only</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>What type of agreement is this?</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>Master MSP</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/transactionTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Business User</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>Country Partner</label>
    </customValue>
    <customValue>
        <fullName>Direct Market Reseller (DMR)</fullName>
    </customValue>
    <customValue>
        <fullName>Distribution Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors Partner Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Home User</fullName>
    </customValue>
    <customValue>
        <fullName>International Master Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Service Provider (MSP)</fullName>
    </customValue>
    <customValue>
        <fullName>Original Equipment Manufacturer (OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Press / Media Evaluator</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Trial User</fullName>
    </customValue>
    <customValue>
        <fullName>Value Added Reseller (VAR)</fullName>
    </customValue>
    <description>Formerly User Type fields that occurs on Account, Lead and Contacts</description>
    <masterLabel>Transaction Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/classes/BatchSsf458UpdateAccounts.cls
/**
  \file         BatchSSf458UpdateAccounts.cls
  \brief        This class will initialise the transactionTypes__c from User_Types__c field.
  \details      SSF-458
  \author       Matt Thompson-Moltzen
  \version      1.0
  \date         24 August 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
*/
global class BatchSsf458UpdateAccounts implements Database.Batchable<SObject>
{
	global Database.QueryLocator start(Database.BatchableContext bc)
	{
		String query = 'SELECT Id, User_Type__c, transactionTypes__c, transactionTypesAsText__c, (SELECT Id, Account__c, Type__c, Status__c FROM Agreements__r) FROM Account';

		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext bc, List<Account> accts)
	{
    Set<String> agreementTypes = new Set<String>();

    agreementTypes.add('Distribution Partner');
    agreementTypes.add('Managed Service Provider (MSP)');
    agreementTypes.add('Original Equipment Manufacturer (OEM)');
    agreementTypes.add('Value Added Reseller (VAR)');

    Set<String> enterpriseTyps = new Set<String>();

    enterpriseTyps.add('Business User');
    enterpriseTyps.add('Trial User');

		for (Account acct : accts) {
      Set<String> typs = new Set<String>();

  		if (acct.transactionTypes__c == null) {
    		if 			(acct.User_Type__c == null)														{ typs.add('Other'); }
    		else if (acct.User_Type__c == 'Both MSP and VAR') 						{ typs.add('Channel Partner'); } // has one of the agreement types potentially
    		else if (agreementTypes.contains(acct.User_Type__c) == false) { typs.add(acct.User_Type__c); }
    		else 																													{ typs.add('Channel Partner'); } // has one of the agreement types potentially

        Integer nMsp 				 	= 0;
    		Integer nOem 				 	= 0;
    		Integer nVar 				 	= 0;
    		Integer nDistribution = 0;

        for (Agreement__c agt : acct.Agreements__r) {
          if (agt.Status__c != 'Inactive' && agt.Status__c != 'Terminated' && agt.Status__c != 'Expired') {
            if      (agt.Type__c == 'Cloud')        { nMsp++; }
            else if (agt.Type__c == 'MSP')          { nMsp++; }
            else if (agt.Type__c == 'Master MSP')   { nMsp++; }
            else if (agt.Type__c == 'OEM')          { nOem++; }
            else if (agt.Type__c == 'Reseller')     { nVar++; }                   // SSF-533
            else if (agt.Type__c == 'VAR')          { nVar++; }                   // deprecated in SSF-533
            else if (agt.Type__c == 'Distribution') { nDistribution++; }
          }
        }

    		if (nMsp > 0) 				 { typs.add('Channel Partner'); typs.add('Managed Service Provider (MSP)'); }
    		if (nOem > 0) 				 { typs.add('Channel Partner'); typs.add('Original Equipment Manufacturer (OEM)'); }
    		if (nVar > 0) 				 { typs.add('Channel Partner'); typs.add('Value Added Reseller (VAR)'); }
    		if (nDistribution > 0) { typs.add('Channel Partner'); typs.add('Distribution Partner'); }

        if (typs.contains('Channel Partner')) { typs.removeAll(enterpriseTyps); } // remove Enterprise types to avoid validation issues

        List<String> l = new List<String>(typs);

    		String s = String.join(l, ';');

    		acct.transactionTypes__c       = s;
        acct.transactionTypesAsText__c = s;
  		}
    }

    AccountTriggerHandler.disableTrigger();

		try {
			update accts;
		}
		catch (DmlException e) {
			System.debug(LoggingLevel.ERROR, 'BatchSsf458UpdateAccounts::execute() exception: ' + e.getMessage());
		}

    AccountTriggerHandler.enableTrigger();
	}

	global void finish(Database.BatchableContext bc)
	{
		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :bc.getJobId()];

		System.debug(LoggingLevel.INFO, 'BatchSsf458UpdateAccounts::finish() Status=' + a.Status + ' TotalJobItems=' + a.TotalJobItems + ' JobItemsProcessed=' + a.JobItemsProcessed + ' NumberOfErrors= ' + a.NumberOfErrors);
	}

}