mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NFR_ShadowProtect_Desktop_Serial__c</fullName>
        <label>NFR ShadowProtect Desktop Serial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFR_ShadowProtect_ImageManager_Serial__c</fullName>
        <label>NFR ShadowProtect ImageManager Serial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFR_ShadowProtect_SPX_Linux__c</fullName>
        <label>NFR ShadowProtect SPX - Linux</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFR_ShadowProtect_Server_Serial__c</fullName>
        <label>NFR ShadowProtect Server Serial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/objects/Language__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported languages names and language ISO codes</description>
    <label>Language</label>
</CustomObject>

mdapi/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licenses (Account)</relationshipLabel>
        <relationshipName>Licensing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activation__c</fullName>
        <inlineHelpText>License Activation Date</inlineHelpText>
        <label>Activation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration__c</fullName>
        <inlineHelpText>Key Expiration</inlineHelpText>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Portugal)</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Chinese Traditional</fullName>
                </value>
                <value>
                    <fullName>Chinese Simplified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Linux__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Linux</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License Manager</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>License Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Key Type</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>SPX Linux</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Image Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Product Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/classes/NFRKeys.cls
global with sharing class NFRKeys {     
    public String Error = ''; 
    
    public NFRKeys() {
    }
    
    public Boolean createPartnerBaseKeys(Id accountId, String language) {
        System.debug('NFRKeys.createPartnerBaseKeys ' + accountId + ', ' + language);
        Error = '';
        License__c license;
        Account a = null;                
        String Server = null;
        String Desktop = null;
        String SPX_Linux = null;
        String ImageManager = null;
        List<License__c> Licenses = new List<License__c>();
        
        try {
            a = [SELECT Id,
                 NFR_ShadowProtect_Desktop_Serial__c, 
                 NFR_ShadowProtect_Server_Serial__c, 
                 NFR_ShadowProtect_SPX_Linux__c, 
                 NFR_ShadowProtect_ImageManager_Serial__c
                 FROM Account
                 WHERE Id = :accountId];
            
            Desktop = a.NFR_ShadowProtect_Desktop_Serial__c;
            Server = a.NFR_ShadowProtect_Server_Serial__c;
            SPX_Linux = a.NFR_ShadowProtect_SPX_Linux__c;
            ImageManager = a.NFR_ShadowProtect_ImageManager_Serial__c;
            
            Date expires = Date.today().addYears(1);
                   
            if (String.isBlank(Desktop)) {           
                license = create(accountId, 'Desktop', 1, false, expires, language, 'Onboarding');
                if (license != null) {
                    licenses.Add(license);
                    Desktop = license.Name;
                }
            }
    
            if (String.isBlank(Server)) {
                license = create(accountId, 'Server', 2, false, expires, language, 'Onboarding');
                if (license != null) {
                    licenses.Add(license);
                    Server = license.Name;
                }
            }     
    
            if (String.isBlank(SPX_Linux)) {            
                license = create(accountId, 'SPX Linux', 2, true, expires, language, 'Onboarding');
                if (license != null) {
                    licenses.Add(license);
                    SPX_Linux = license.Name;
                }
            }         
    
            if (String.isBlank(ImageManager)) {            
                license = create(accountId, 'Image Manager', 7, false, expires, language, 'Onboarding');
                if (license != null) {
                    licenses.Add(license);
                    ImageManager = license.Name;
                }
            }       
        } catch (Exception e) {
            Error = 'Exception: ' + e.getMessage() + '\r\n ' + e.getStackTraceString();
            System.debug(Error);
        }
        
        if (a != null && licenses.size() > 0) {
            insert licenses;
            
            System.debug('Keys:\r\n  Desktop:       ' + Desktop + '\r\n  Server:        ' + Server + '\r\n  SPX Linux:     ' + SPX_Linux + '\r\n  Image Manager: ' + ImageManager);

            a.NFR_ShadowProtect_Desktop_Serial__c = Desktop;
            a.NFR_ShadowProtect_Server_Serial__c = Server;
            a.NFR_ShadowProtect_SPX_Linux__c = SPX_Linux;
            a.NFR_ShadowProtect_ImageManager_Serial__c = ImageManager;
            
          	update a;
        }
        
        return (null != Desktop && null != Server && null != SPX_Linux && null != ImageManager);
    }
    
    public License__c create(ID accountId, String product, Integer productId, Boolean isLinux, Date expires, String language, String origin) {         
    	NFRKeyCallout callout = new NFRKeyCallout();
        String key = callout.makeCall('New', '', expires, Languages.determineNumber(language), productId, isLinux, accountId, language, product);
        
        if (Pattern.matches('[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}', key)) {
            License__c license = new License__c(
                Name = key,
                Status__c = 'Active',
                Class__c = 'NFR',
                Expiration__c = expires,
                Language__c = language,
                Type__c = product,
                Linux__c = islinux,
                Activation__c = Date.today(),
                Account__c = accountId,
                Origin__c = origin);            
            return license;
        }
        return null;
    }
}