mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionTypesAsText__c</fullName>
        <description>This is a text version of the Multi-Picklist transactionTypes__c field that can be used in formulae. It is not intended to be displayed or updated directly.</description>
        <label>Transaction Types (text)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionTypes__c</fullName>
        <inlineHelpText>Some of the Transaction Types will be automatically managed depending on any Agreements in place</inlineHelpText>
        <label>Transaction Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>transactionTypes</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/transactionTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Business User</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>Country Partner</label>
    </customValue>
    <customValue>
        <fullName>Direct Market Reseller (DMR)</fullName>
    </customValue>
    <customValue>
        <fullName>Distribution Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors Partner Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Home User</fullName>
    </customValue>
    <customValue>
        <fullName>International Master Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Service Provider (MSP)</fullName>
    </customValue>
    <customValue>
        <fullName>Original Equipment Manufacturer (OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Press / Media Evaluator</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Trial User</fullName>
    </customValue>
    <customValue>
        <fullName>Value Added Reseller (VAR)</fullName>
    </customValue>
    <description>Formerly User Type fields that occurs on Account, Lead and Contacts</description>
    <masterLabel>Transaction Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/classes/BatchUpdateAccountPartnerLevelsTest.cls
/**
  \file         BatchUpdateAccountPartnerLevelsTest.cls
  \brief        This class is written for code coverage.
  \details      SSF-400
  \author       Sean Oldroyd
  \version      1.2
  \date         30 August 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1       2017-08-24  Matt Thompson-Moltzen   Modified to process Accounts!
  1.2       2017-08-30  Matt Thompson-Moltzen   Changed references to User_Type__c to transactionTypesAsText__c (SSF-458).
*/
@isTest
public with sharing class BatchUpdateAccountPartnerLevelsTest
{
  static testMethod void testBatchUpdateAccountPartnerLevels()
  {
    List<Account> accts = new List<Account>();

    Integer i = 0;

    for (i = 0; i < 200; i++) {
      Account acct = new Account();

      acct.Name                = 'Company-' + i;
      acct.transactionTypes__c = 'Business User';
      acct.BillingCity         = 'Draper';
      acct.BillingState        = 'UT';
      acct.BillingPostalCode   = '84020';
      acct.BillingCountry      = 'US';

      accts.add(acct);
    }

    AccountTriggerHandler.disableTrigger();

    insert accts;

    AccountTriggerHandler.enableTrigger();

    Test.startTest();

    BatchUpdateAccountPartnerLevels buapl = new BatchUpdateAccountPartnerLevels();

    DataBase.executeBatch(buapl);

    Test.stopTest();
  }
}