mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Level_Calculated__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <inlineHelpText>The calculated Partner Level determined by sales and certifications</inlineHelpText>
        <label>Partner Level - Calculated</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Level_Overwritten__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the Partner Level overwriting the calculated Partner Level?</inlineHelpText>
        <label>Partner Level Overwritten?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Level__c</fullName>
        <description>Imported from Workbench</description>
        <label>Partner Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Authorized</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAR_Agreement_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Application Submitted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapi/objects/Agreement__c.object
<CustomObject>
    <description>Account accepted agreements.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account related to this agreement</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the Agreement</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cash Only</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PartnerLevelManager.cls
/**
  \file         PartnerLevelManagerTest.apcx
  \brief        Set and Account's Partner Level based on account values.
  \details      JIRA ticket(s): SSF-545, SSF-621
                Code has changed from previous version because the "End User" account Type
                no longer exists and just eliminating that would have all Accounts have 
                a mimimum of 'Authorized'.  In ticket 545, Matt Harding asks for the User Types
                to have a minimum of 'Authorized'.
  \author       Loch MacLeod
  \version      1.0
  \date         22 September 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
*/
public class PartnerLevelManager {  
    private static String AccountUserTypes = 'Both MSP and VAR;Direct Market Reseller (DMR);Managed Service Provider (MSP);Value Added Reseller (VAR);Alliance Partner;Original Equipment Manufacturer (OEM);';
    
    //
    // setPartnerLevel sets an Account's Partner Level.
    //             
    // For an Account to have a minimum Partner Level of 'Authorized' 
    // it must have at least ONE of the following:
    //     * Be in the list of User Types
    //     * An Account Number (NavId)
    //     * VAR_Agreement_Accepted__c set to true
    //     * An active Agreement
    // 
    public static void setPartnerLevel(List<Account> listNew) {
        List<Id> accountIds = new List<Id>();
        
        for (Account a : listNew) {
            accountIds.add(a.Id);
        }
        
        // ??? Should it be certain types of agreements ???        
        Map<Id, Account> accountAgreements = new Map<Id, Account>([SELECT Id, (SELECT Id FROM Agreements__r WHERE Status__c = 'Active') FROM Account WHERE Id IN :accountIds]);
        
        Boolean isPartner = false;
        for (Account a : listNew) {
            System.debug('User Type      ' + a.User_Type__c);
            System.debug('AccountNumber  ' + a.AccountNumber);
            System.debug('VAR Agreement  ' + a.VAR_Agreement_Accepted__c);

            if ((!String.isBlank(a.User_Type__c) && AccountUserTypes.contains(a.User_Type__c)) ||
                !String.isBlank(a.AccountNumber) ||                
                a.VAR_Agreement_Accepted__c ||
                (accountAgreements.get(a.Id) != null && 
                accountAgreements.get(a.Id).Agreements__r != null &&
                0 < accountAgreements.get(a.Id).Agreements__r.size())) {
                if (String.isBlank(a.Partner_Level_Calculated__c) || 'None'.equals(a.Partner_Level_Calculated__c)) {
                    // Minimum Partner Level of "Authorized"
                    a.Partner_Level_Calculated__c = 'Authorized';
                }
            } 
            else {
                // Account is not a Partner
                a.Partner_Level_Calculated__c = 'None';
            }

            if (!a.Partner_Level_Overwritten__c) {
                // If Partner Level has not been overwritten it must be the same as Calculated
                a.Partner_Level__c = a.Partner_Level_Calculated__c;
            }
            
            System.debug('Partner_Level_Calculated__c  ' + a.Partner_Level_Calculated__c);
            System.debug('Partner_Level__c             ' + a.Partner_Level__c);
        }
    }
}