mdapi/objects/Account.object
<CustomObject>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>High_Potential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Account to be treated as Gold/Platinum for assignment?</inlineHelpText>
        <label>High Potential</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Promote_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Have the territory assignment rules treat this Account as Gold/Platinum?</inlineHelpText>
        <label>Promote Account</label>
        <type>Checkbox</type>
    </fields>

mdapi/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Additional_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Additional_Domain__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>PacWest</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>South Asia</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Canada - East</fullName>
                </value>
                <value>
                    <fullName>Canada - West</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>Partner</businessProcess>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi/objects/StcZone__c.object
<CustomObject>
    <description>Object to hold Global Region, Region, Territory</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this StcZone active?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_Accounts_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who gets assigned new Accounts for the Territory</inlineHelpText>
        <label>Assign Accounts To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StcZones1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who gets assigned new Leads for the Territory</inlineHelpText>
        <label>Assign Leads To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>StcZones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Controlling_Office__c</fullName>
        <label>Controlling Office</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cork, IE</fullName>
                </value>
                <value>
                    <fullName>Draper, Utah  US</fullName>
                </value>
                <value>
                    <fullName>Sydney, NSW AU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
    <label>StcZone</label>
    <nameField>
        <label>StcZone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StcZones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/StcZoneRule__c.object
<CustomObject>
    <fields>
        <fullName>Account_User_Types__c</fullName>
        <inlineHelpText>When processing an Account, which User Types apply.  Leave blank to allow any.</inlineHelpText>
        <label>Account User Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Should this Rule be applied</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Countries__c</fullName>
        <inlineHelpText>Comma separated list of countries</inlineHelpText>
        <label>Countries</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>High_Potential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this Account for High Potential, Gold or Platinum only?</inlineHelpText>
        <label>High Potential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_User_Types__c</fullName>
        <inlineHelpText>Select the User Types which apply to this Rule when processing a Lead.  Leave empty if any User Type is allowed.</inlineHelpText>
        <label>Lead User Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>1000</defaultValue>
        <inlineHelpText>Order in which this Rule is applied</inlineHelpText>
        <label>Order</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Postal_Codes__c</fullName>
        <inlineHelpText>Commas separated list of Postal Codes or single Function</inlineHelpText>
        <label>Postal Codes</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <inlineHelpText>Comma separated list of states</inlineHelpText>
        <label>States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StcZone__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>StcZone</label>
        <referenceTo>StcZone__c</referenceTo>
        <relationshipLabel>StcZoneRules</relationshipLabel>
        <relationshipName>StcZoneRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Works_On__c</fullName>
        <defaultValue>&quot;Both Leads and Accounts&quot;</defaultValue>
        <inlineHelpText>Does this rule apply to leads, accounts or both?</inlineHelpText>
        <label>Works On</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Both Leads and Accounts</fullName>
                </value>
                <value>
                    <fullName>Accounts Only</fullName>
                </value>
                <value>
                    <fullName>Leads Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>StcZoneRule</label>
    <nameField>
        <label>StcZoneRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StcZoneRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/globalValueSets/Global_Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AMER</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <masterLabel>Global Region</masterLabel>
</GlobalValueSet>

mdapi/globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US North</fullName>
    </customValue>
    <customValue>
        <fullName>US South</fullName>
    </customValue>
    <customValue>
        <fullName>US West</fullName>
    </customValue>
    <customValue>
        <fullName>Australia / New Zealand</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/classes/StcZoneManagerTest.cls
/**
  \file         StcZoneManagerTest.apxc
  \brief        Test methods for the StcZone custom object
  \details      Runs test for Leads and Accounts and StcZone custom object
                SSF-227
  \author       Loch MacLeod
  \version      1.10
  \date         30 June 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1                   Anthony Heber           Updated to remove SeeAllData=true to improve test runtime and reliability, added new test for assignment rule conflicts
  1.2       2017-07-17  Loch MacLeod            SSF-383  Added test for User Types
  1.3       2017-07-19  Loch MacLeod            SSF-395, SSF-402 - Added tests for Promote_Account__c and corrected Account assignment
  1.4       2017-07-25  Loch MacLeod            SSF-413  Opportunity territory and assignment
  1.5       2017-08-23  Loch MacLeod            SSF-559  New Test for User Type should be OR'd with High Potential, not AND'd
  1.6       2017-08-23  Loch MacLeod            SSF-585  High Potential only allowed if Account User Type
  1.7       2017-08-30  Loch MacLeod            SSF-593  Change Account User Type calls to Transaction Types
  1.8       2017-08-30  Loch MacLeod            SSF-559  Fix assignment rules
  1.9       2017-09-27  Loch MacLeod            SSF-593  Transaction Types back in
  1.10      2017-09-28  Loch MacLeod            SSF-550  Corrections Lead Assignment.
*/
@isTest
public class StcZoneManagerTest {
    static String User1Name = 'user1@StcZoneManagerTestExample.com';
    static String User2Name = 'user2@StcZoneManagerTestExample.com';
    static String User3Name = 'user3@StcZoneManagerTestExample.com';
    static User user1;
    static User user2;
    static User user3;
    
    @testSetup
    static void testSetup() {
        Stc.setTestSettings();
        
        Map<String, StcZone__c> zones = new Map<String, StcZone__c>();
        Profile p = [select Id from Profile where Name = 'System Administrator'];
        
        user1 = new User(Username = User1Name,
                         Email = User1Name,
                         Alias = 'stczone1',
                         CommunityNickname = 'stczone1',
                         TimeZoneSidKey = 'GMT',
                         LocaleSidKey = 'en_US',
                         EmailEncodingKey = 'UTF-8',
                         LanguageLocaleKey = 'en_US',
                         FirstName = 'Test', 
                         LastName = 'User1',
                         ProfileId = p.Id);
                
        user2 = new User(Username = User2Name,
                         Email = User2Name,
                         Alias = 'stczone2',
                         CommunityNickname = 'stczone2',
                         TimeZoneSidKey = 'GMT',
                         LocaleSidKey = 'en_US',
                         EmailEncodingKey = 'UTF-8',
                         LanguageLocaleKey = 'en_US',
                         FirstName = 'Test', 
                         LastName = 'User2',
                         ProfileId = p.Id);
                
        user3 = new User(Username = User3Name,
                         Email = User3Name,
                         Alias = 'stczone3',
                         CommunityNickname = 'stczone3',
                         TimeZoneSidKey = 'GMT',
                         LocaleSidKey = 'en_US',
                         EmailEncodingKey = 'UTF-8',
                         LanguageLocaleKey = 'en_US',
                         FirstName = 'Test', 
                         LastName = 'User2',
                         ProfileId = p.Id);
        
        List<User> users = new List<User>();
        users.add(user1);
        users.add(user2);
        users.add(user3);

        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert users;
        }
       
        Additional_Domain__c d = new Additional_Domain__c(Name = 'test.com');
        Insert d;        
        // OEM
        zones.put('US OEM',
                  new StcZone__c(Name = 'US OEM',
                                 Region__c = 'US West',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'US OEM',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        // Silver Pacific
        zones.put('Silver Pacific',
                  new StcZone__c(Name = 'Silver Pacific',
                                 Region__c = 'US West',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Silver Pacific',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        // Los Angeles
        zones.put('Los Angeles',
                  new StcZone__c(Name = 'Los Angeles',
                                 Region__c = 'US West',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Los Angeles',
                                 Assign_To__c = user2.Id,
                                 Assign_Accounts_To__c = user2.Id));   
       zones.put('Pacific Northwest',
                 new StcZone__c(Name = 'Pacific Northwest',
                                 Region__c = 'US West',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Pacific Northwest',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user2.Id));
        // Silver Northeast
        zones.put('Silver Northeast',
                  new StcZone__c(Name = 'Silver Northeast',
                                 Region__c = 'US North',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Silver Northeast',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        // Silver Great Lakes
        zones.put('Silver Great Lakes',
                  new StcZone__c(Name = 'Silver Great Lakes',
                                 Region__c = 'US North',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Silver Great Lakes',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        // Germany North
        zones.put('Germany North',
                  new StcZone__c(Name = 'Germany North',
                                 Region__c = 'Germany',
                                 Global_Region__c = 'EMEA', 
                                 Controlling_Office__c = 'Cork, IE', 
                                 Active__c = true, 
                                 Territory__c = 'Germany North',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        // Germany South
        zones.put('Germany South',
                  new StcZone__c(Name = 'Germany South',
                                 Region__c = 'Germany',
                                 Global_Region__c = 'EMEA', 
                                 Controlling_Office__c = 'Cork, IE', 
                                 Active__c = true, 
                                 Territory__c = 'Germany South',
                                 Assign_To__c = user1.Id,
                                 Assign_Accounts_To__c = user1.Id));
        // Unknown
/*
        zones.put('Unknown',
                  new StcZone__c(Name = 'Unknown',
                                 Region__c = 'US West',
                                 Global_Region__c = 'AMER', 
                                 Controlling_Office__c = 'Draper, Utah  US', 
                                 Active__c = true, 
                                 Territory__c = 'Unknown',
                                 Assign_To__c = user3.Id,
                                 Assign_Accounts_To__c = user3.Id));
 */                                

        insert zones.values();
        
        List<StcZoneRule__c> zoneRules = new List<StcZoneRule__c>();
         
        zoneRules.add(new StcZoneRule__c(Order__c = 100,
                                         Active__c = true,
                                         Name = 'Germany North 1',
                                         StcZone__c = zones.get('Germany North').Id,
                                         Countries__c = 'DE',
                                         States__c = null,
                                         Postal_Codes__c = 'STARTSWITH 6:7:8:9',
                                         Works_On__c = 'Leads Only',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 200,
                                         Active__c = true,
                                         Name = 'Germany North 2',
                                         StcZone__c = zones.get('Germany North').Id,
                                         Countries__c = 'DE',
                                         States__c = null,
                                         Postal_Codes__c = 'BETWEEN 20000:29999',
                                         Works_On__c = 'Leads Only',                                            
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 300,
                                         Active__c = true,
                                         Name = 'Germany South',
                                         StcZone__c = zones.get('Germany South').Id,
                                         Countries__c = 'DE',
                                         States__c = null,
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 1000,
                                         Active__c = true,
                                         Name = 'US OEM',
                                         StcZone__c = zones.get('US OEM').Id,
                                         Countries__c = 'US,CA',
                                         States__c = null,
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Accounts Only',                                 
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = 'Alliance Partner',
                                         High_Potential__c = false    
                                        )); 
        zoneRules.add(new StcZoneRule__c(Order__c = 2000,
                                         Active__c = true,
                                         Name = 'Pacific Northwest',   
                                         StcZone__c = zones.get('Pacific Northwest').Id,
                                         Countries__c = 'US',
                                         States__c = 'CA,ID,OR,WA',
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Accounts Only',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = 'Trial User;Business User',
                                         High_Potential__c = true
                                        ));
        zoneRules.add(new StcZoneRule__c(Order__c = 3000,
                                         Active__c = true,
                                         Name = 'Los Angeles 1',
                                         StcZone__c = zones.get('Los Angeles').Id,
                                         Countries__c = 'US',
                                         States__c = 'CA',
                                         Postal_Codes__c = '94216,94215,94217,94218,94219,94220',                                         
                                         Works_On__c = 'Both Leads and Accounts',                                         
                                         Lead_User_Types__c = 'Trial User;Business User',
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 4000,
                                         Active__c = true,
                                         Name = 'Los Angeles 2',
                                         StcZone__c = zones.get('Los Angeles').Id,
                                         Countries__c = 'US',
                                         States__c = 'CA',
                                         Postal_Codes__c = '94116,94115,94117,94118,94119,94120',                                         
                                         Works_On__c = 'Both Leads and Accounts',               
                                         Lead_User_Types__c = 'Trial User;Business User',
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));       
        zoneRules.add(new StcZoneRule__c(Order__c = 5000,
                                         Active__c = true,
                                         Name = 'Silver Pacific',
                                         StcZone__c = zones.get('Silver Pacific').Id,
                                         Countries__c = 'US',
                                         States__c = 'WA,OR,CA,NV,AZ',
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 6000,
                                         Active__c = true,
                                         Name = 'Silver Northeast',
                                         StcZone__c = zones.get('Silver Northeast').Id,
                                         Countries__c = 'US',
                                         States__c = 'ME,RI,NH,NY,NJ,CT,RI,VT',
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Leads Only',
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false                                         
                                         )); 
        zoneRules.add(new StcZoneRule__c(Order__c = 7000,
                                         Active__c = true,
                                         Name = 'Silver Great Lakes 1',
                                         StcZone__c = zones.get('Silver Great Lakes').Id,
                                         Countries__c = 'CA',
                                         States__c = 'MB, ON, QC, NL, MB, PE, NS',
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
        zoneRules.add(new StcZoneRule__c(Order__c = 8000,
                                         Active__c = true,
                                         Name = 'Silver Great Lakes 2',
                                         StcZone__c = zones.get('Silver Great Lakes').Id,
                                         Countries__c = 'US',
                                         States__c = 'WI, MI, MN',
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
/*                                         
        zoneRules.add(new StcZoneRule__c(Order__c = 100000,
                                         Active__c = true,
                                         Name = 'Catch All',
                                         StcZone__c = zones.get('Unknown').Id,
                                         Countries__c = null,
                                         States__c = null,
                                         Postal_Codes__c = null,
                                         Works_On__c = 'Both Leads and Accounts',                                
                                         Lead_User_Types__c = null,
                                         Account_User_Types__c = null,
                                         High_Potential__c = false
                                         ));
*/                                         

        insert zoneRules;
    }

    @isTest
    static void testLead_Basic() {        
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Basic',
            Company = 'Basic Campaign Company',
            Email = 'test.basic@test.com',
            State = 'CA',
            Country = 'US',
            PostalCode = '98765-0964',
            UserType__c = 'Value Added Reseller (VAR)');
        insert testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];      
        System.assertEquals('Silver Pacific', testLead.StcZone_Territory__c);   
    }

    @isTest
    static void testLead_ChangeAddress() {
        Lead testLead = new Lead(
            FirstName = 'Lead',
            LastName = 'Change',
            Company = 'Change Campaign Company',
            Email = 'lead.cange@test.com',
            State = 'CA',
            Country = 'US',
            PostalCode = '91917',
            UserType__c = 'Value Added Reseller (VAR)');
        insert testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];

        System.assertEquals('Silver Pacific', testLead.StcZone_Territory__c);
        
        testLead.State = 'NY';
        testLead.PostalCode = '14535';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Silver Northeast', testLead.StcZone_Territory__c);   
    }
    
    @isTest
    static void testLead_CA() {
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'CA',
            Company = 'CA ampaign Company',
            Email = 'test.ca@test.com',
            State = 'ON',
            Country = 'CA',
            PostalCode = 'P0M 0B8',
            UserType__c = 'Value Added Reseller (VAR)');
        insert testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Silver Great Lakes', testLead.StcZone_Territory__c);   
    }

    @isTest
    static void testLead_BETWEEN() {
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Test',
            Company = 'Test Campaign Company',
            Email = 'test.test@test.com',
            Country = 'DE',
            PostalCode = '59000',
            UserType__c = 'Value Added Reseller (VAR)');
        insert testLead;
              
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany South', testLead.StcZone_Territory__c); 
        
        testLead.PostalCode = '25987';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany North', testLead.StcZone_Territory__c);  
        
        testLead.PostalCode = '30000';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany South', testLead.StcZone_Territory__c); 

        testLead.PostalCode = '20000';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany North', testLead.StcZone_Territory__c);     
        
        testLead.PostalCode = '29999';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany North', testLead.StcZone_Territory__c);
    } 

    @isTest
    static void testLead_STARTSWITH() {
        Lead testLead = new Lead(
            FirstName = 'Test',
            LastName = 'Test',
            Company = 'Test Campaign Company',
            Email = 'test.test@test.com',
            Country = 'DE',
            PostalCode = '59000',
            UserType__c = 'Value Added Reseller (VAR)');
        insert testLead;
              
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany South', testLead.StcZone_Territory__c); 
        
        testLead.PostalCode = '78987';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Germany North', testLead.StcZone_Territory__c); 
    } 
   
    @isTest
    static void testLead_AssignRule() {
        Lead testLead = new Lead(
            FirstName = 'Lead',
            LastName = 'Test',
            Company = 'Laad Campaign Company',
            Email = 'lead.test@test.com',
            State = 'NY',
            Country = 'US',
            PostalCode = '14535',
            UserType__c = 'Value Added Reseller (VAR)');
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.assignmentRuleHeader.useDefaultRule= true;
        testLead.setOptions(dmo);
        Test.startTest();
        insert testLead;
        Test.stopTest();
              
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c, Owner.Name FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Silver Northeast', testLead.StcZone_Territory__c);
        // Refuses to pass tests, does work when async isn't in the same overall transaction
        //System.assertEquals('Test User1', testLead.Owner.Name);
    } 

    @isTest
    static void testLead_UserType() {        
        Lead testLead = new Lead(
            FirstName = 'Lead',
            LastName = 'Test',
            Company = 'Laad Campaign Company',
            Email = 'lead.test@test.com',
            State = 'CA',
            Country = 'US',
            PostalCode = '94118-1234',
            UserType__c = 'Business User');
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.assignmentRuleHeader.useDefaultRule= true;
        testLead.setOptions(dmo);
        Test.startTest();
        insert testLead;
        Test.stopTest();
              
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c, Owner.Name FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Los Angeles', testLead.StcZone_Territory__c);
        
        testLead.UserType__c = 'Both MSP and VAR';
        update testLead;
        
        testLead = [SELECT Id, Country, State, PostalCode, StcZone_Territory__c, Owner.Name FROM Lead WHERE Id = :testLead.Id];
        System.assertEquals('Silver Pacific', testLead.StcZone_Territory__c);
    }   

    @isTest
    static void testOpp_PartnerAccount() {
        // Los Angeles
        Account testPartner = new Account(
            Name = 'Opp Account2',
            Type = 'Partner',
            AccountNumber = 'OppAcc2',
            Partner_Level__c = 'Gold', 
            Partner_Level_Calculated__c = 'Gold',
            Partner_Level_atQuarter__c = 'Gold',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'CA',
            BillingCountry = 'US',
            BillingPostalCode = '94118',
            High_Potential__c = false,
            User_Type__c = 'Business User',
            transactionTypes__c = 'Business User',
            transactionTypesAsText__c = 'Business User'
        );
        // Silver Pacific
        Account testAccount = new Account(
            Name = 'Opp Account1',
            Type = 'End User',
            AccountNumber = 'OppAcc1',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_atQuarter__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'NV',
            BillingCountry = 'US',
            BillingPostalCode = '90118',
            High_Potential__c = false,
            User_Type__c = 'Managed Service Provider (MSP)',
            transactionTypes__c = 'Managed Service Provider (MSP)',
            transactionTypesAsText__c = 'Managed Service Provider (MSP)'
        );
        
        List<Account> accounts = new List<Account>();
        accounts.add(testPartner);
        accounts.add(testAccount);
        insert accounts;
                        
        testPartner = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testPartner.Id];
        System.assertEquals('Pacific Northwest', testPartner.StcZone_Territory__c);
        testAccount = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];         
        System.assertEquals('Silver Pacific', testAccount.StcZone_Territory__c);
       
        Opportunity opp = new Opportunity(
            Type = 'Partner',
            AccountId = testAccount.Id,
            Partner__c = testPartner.Id,
            Name = 'Opportunity Account',
            BudgetAmount__c = 1234.00,
            CloseDate = Date.Today(),
            EstCloseDate__c = Date.Today(),           
            StageName = 'Suspect'
        );
        insert opp;
        
        opp = [SELECT Id, OwnerId, StcZone_Territory__c FROM Opportunity WHERE Id = :opp.Id];        
        System.assertEquals('Pacific Northwest', opp.StcZone_Territory__c);
        
        User user_2 = [SELECT Id, Name FROM User WHERE UserName = :User2Name];       
        System.assertEquals(user_2.Id, opp.OwnerId); 
    }

    @isTest
    static void testAccount_HighPotential() {
        Account testAccount = new Account(
            Name = 'Account Trigger Testing',
            Type = 'Account',
            AccountNumber = 'ABCD',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'CA',
            BillingCountry = 'US',
            BillingPostalCode = '94444',
            High_Potential__c = false,
            User_Type__c = 'Managed Service Provider (MSP)',
            transactionTypes__c = 'Managed Service Provider (MSP)',
            transactionTypesAsText__c = 'Managed Service Provider (MSP)'
        );
        insert testAccount;
        
        testAccount = [SELECT Id, Owner.Name, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];      
        System.assertEquals('Silver Pacific', testAccount.StcZone_Territory__c);
        
        testAccount.High_Potential__c = true;
        update testAccount;
        
        testAccount = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];      
        System.assertEquals('Pacific Northwest', testAccount.StcZone_Territory__c);
    }

    @isTest
    static void testAccount_UserType() {
        System.debug('testAccount_UserType');
        Account testAccount = new Account(
            Name = 'Account Trigger Testing',
            Type = 'Account',
            AccountNumber = 'ABCD',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'CA',
            BillingCountry = 'US',
            BillingPostalCode = '94117',
            High_Potential__c = false,
            User_Type__c = 'Alliance Partner',
            transactionTypes__c = 'Alliance Partner',
            transactionTypesAsText__c = 'Alliance Partner'
        );
        insert testAccount;
        
        testAccount = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];      
        System.assertEquals('US OEM', testAccount.StcZone_Territory__c);     
    }
 
    @isTest
    static void testAccount_UserType2() {
        System.debug('***************************************************************');
        System.debug('testAccount_UserType2');
        Account testAccount = new Account(
            Name = 'Account User Type Test',
            Type = 'Account',
            AccountNumber = '12CD',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Everest',
            BillingState = 'WA',
            BillingCountry = 'US',
            BillingPostalCode = '00090',
            High_Potential__c = true,
            User_Type__c = 'Value Added Reseller (VAR)',
            transactionTypes__c = 'Value Added Reseller (VAR);Managed Service Provider (MSP)',
            transactionTypesAsText__c = 'Value Added Reseller (VAR);Managed Service Provider (MSP)'
        );
        insert testAccount;
        System.debug('---------------------------------------------------------------');
        
        testAccount = [SELECT Id, Owner.Name, StcZone_Territory__c, transactionTypesAsText__c FROM Account WHERE Id = :testAccount.Id];      
        System.debug('transactionTypesAsText__c' + testAccount.transactionTypesAsText__c);
        System.assertEquals('Pacific Northwest', testAccount.StcZone_Territory__c);
        System.assertEquals('Test User2', testAccount.Owner.Name);   
        
        testAccount.High_Potential__c = false;
        update testAccount;
        
        testAccount = [SELECT Id, Owner.Name, StcZone_Territory__c, transactionTypesAsText__c FROM Account WHERE Id = :testAccount.Id];      
        System.debug('transactionTypesAsText__c' + testAccount.transactionTypesAsText__c);
        System.assertEquals('Silver Pacific', testAccount.StcZone_Territory__c);
        System.assertEquals('Test User1', testAccount.Owner.Name); 
        System.debug('***************************************************************');
    }

    @isTest
    static void testAccount_PromoteAccount() {
        Account testAccount = new Account(
            Name = 'Account Trigger Testing',
            Type = 'Account',
            AccountNumber = 'ABCD',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'CA',
            BillingCountry = 'US',
            BillingPostalCode = '94118',
            High_Potential__c = false,
            User_Type__c = 'Value Added Reseller (VAR)',
            transactionTypes__c = 'Value Added Reseller (VAR)',
            transactionTypesAsText__c = 'Value Added Reseller (VAR)'
        );
        insert testAccount;
        
        testAccount = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];      
        System.assertEquals('Los Angeles', testAccount.StcZone_Territory__c);
        
        testAccount.Promote_Account__c = true;
        update testAccount;
        
        testAccount = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];      
        System.assertEquals('Pacific Northwest', testAccount.StcZone_Territory__c);
    }
   
    @isTest
    static void testAccount_NotFound() {
        Account testAccount = new Account(
            Name = 'Account NotFound',
            Type = 'Account',
            AccountNumber = 'ABCD',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = null,
            BillingState = null,
            BillingCountry = 'ZZ',
            BillingPostalCode = 'H897hj',
            High_Potential__c = false,
            User_Type__c = 'Value Added Reseller (VAR)',
            transactionTypes__c = 'Value Added Reseller (VAR)',
            transactionTypesAsText__c = 'Value Added Reseller (VAR)'
        );
        insert testAccount;
        
        testAccount = [SELECT Id, StcZone_Territory__c FROM Account WHERE Id = :testAccount.Id];      
//        System.assertEquals('Unknown', testAccount.StcZone_Territory__c);
    }
 
    @isTest
    static void testOpp_Account() {
        Account testAccount = new Account(
            Name = 'Opp Account',
            Type = 'Account',
            AccountNumber = 'Opp Account',
            Partner_Level__c = 'Authorized', 
            Partner_Level_Calculated__c = 'Authorized',
            Partner_Level_Overwritten__c = false,
            BillingCity = 'Holladay',
            BillingState = 'NV',
            BillingCountry = 'US',
            BillingPostalCode = '9117',
            High_Potential__c = false,
            User_Type__c = 'Value Added Reseller (VAR)',
            transactionTypes__c = 'Value Added Reseller (VAR)',
            transactionTypesAsText__c = 'Value Added Reseller (VAR)'
        );

        insert testAccount;        
        System.debug('testAccount: ' + testAccount.Id);
       
        Opportunity opp = new Opportunity(
            Type = 'Partner',
            AccountId = testAccount.Id,
            Partner__c = null,
            Name = 'Opportunity Account',
            BudgetAmount__c = 1234.00,
            CloseDate = Date.Today(),
            EstCloseDate__c = Date.Today(),           
            StageName = 'Suspect'
        ); 
        insert opp;
        
        opp = [SELECT Id, OwnerId, StcZone_Territory__c FROM Opportunity WHERE Id = :opp.Id];        
        System.assertEquals('Silver Pacific', opp.StcZone_Territory__c);
        
        User user_1 = [SELECT Id, Name FROM User WHERE UserName = :User1Name];       
        System.assertEquals(user_1.Id, opp.OwnerId);       
    }
}