mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NFR_ShadowProtect_Desktop_Serial__c</fullName>
        <label>NFR ShadowProtect Desktop Serial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFR_ShadowProtect_ImageManager_Serial__c</fullName>
        <label>NFR ShadowProtect ImageManager Serial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFR_ShadowProtect_SPX_Linux__c</fullName>
        <label>NFR ShadowProtect SPX - Linux</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFR_ShadowProtect_Server_Serial__c</fullName>
        <label>NFR ShadowProtect Server Serial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/objects/Language__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported languages names and language ISO codes</description>
    <label>Language</label>
</CustomObject>

mdapi/objects/Languages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Languages</label>
</CustomObject>

mdapi/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licenses (Account)</relationshipLabel>
        <relationshipName>Licensing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activation__c</fullName>
        <inlineHelpText>License Activation Date</inlineHelpText>
        <label>Activation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration__c</fullName>
        <inlineHelpText>Key Expiration</inlineHelpText>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Portugal)</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Ukrainian</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Chinese Traditional</fullName>
                </value>
                <value>
                    <fullName>Chinese Simplified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Linux__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Linux</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>License Manager</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>License Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Key Type</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>SPX Linux</fullName>
                </value>
                <value>
                    <fullName>Server</fullName>
                </value>
                <value>
                    <fullName>Image Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Product Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/classes/NFRKeyAutomatedCreation.cls
public class NFRKeyAutomatedCreation implements Queueable, Database.AllowsCallouts {

    public static List<License__c> newLicenseList = new List<License__c>();
    public static List<String> types = new List<String>();
    public List<String> params;
    public NFRKeyAutomatedCreation(List<String> param){
      this.params = param;
    }

    public void execute(QueueableContext context) {
      createNewKeys(params);
    }

    @InvocableMethod(label='Create New Keys')
    public static void invokeAutomatedKeys(List<String> param){
      System.enqueueJob(new NFRKeyAutomatedCreation(param));
    }

    public static void createNewKeys(List<String> param)
    {
      map<id,string> accountsToLanguageMap = new map<id,string>();
    	for(string p:param){
        list<string> thisList = p.split(';', -2);
        accountsToLanguageMap.put(thisList[0],thisList[1]);
      }
      Schema.DescribeFieldResult fieldResult = license__c.type__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
      list<account> accounts = [Select Name,Id,NFR_ShadowProtect_Server_Serial__c, NFR_ShadowProtect_Desktop_Serial__c, NFR_ShadowProtect_SPX_Linux__c, NFR_ShadowProtect_ImageManager_Serial__c From Account where id in : accountsToLanguageMap.keySet()];
      list<license__c> ls = new list<license__c>();
      for(account a: accounts){
        for( Schema.PicklistEntry f : ple){
          boolean isLinux = false;
          if(f.getLabel() == 'SPX Linux'){
            isLinux = true;
          }
          NFRKeyCallout callout = new NFRKeyCallout();
          string thisResponse = callout.makeCall('New','None',Date.today().addMonths(12),languageNumFromName(accountsToLanguageMap.get(a.id)),getTypeNum(f.getLabel()),isLinux,a.id,accountsToLanguageMap.get(a.id),f.getLabel());
          if(thisResponse !='Failure'){
            License__c l = new License__c();
            l.Name = thisResponse;
            l.Origin__c = 'User';
            l.Expiration__c = Date.today().addMonths(12);
            l.Language__c = accountsToLanguageMap.get(a.id);
            l.Type__c = f.getLabel();
            l.Linux__c = Islinux;
            l.Class__c = 'NFR';
            l.Activation__c = Date.today();
            l.Status__c = 'Active';
            l.Account__c = a.id;
            ls.add(l);
            if(f.getLabel() == 'Desktop'){
              a.NFR_ShadowProtect_Desktop_Serial__c = thisResponse;
            }
            if(f.getLabel() == 'SPX Linux'){
              a.NFR_ShadowProtect_SPX_Linux__c = thisResponse;
            }
            if(f.getLabel() == 'Image Manager'){
              a.NFR_ShadowProtect_ImageManager_Serial__c = thisResponse;
            }
            if(f.getLabel() == 'Server'){
              a.NFR_ShadowProtect_Server_Serial__c = thisResponse;
            }
          }
        }
      }
      if(ls != null && ls.size() > 0){
        insert ls;
      }
      update accounts;
    }
   public static Integer getTypeNum(String typeName)
    {
        //system.debug('in getTypeNum(): typename: '+typeName);
        if(typeName == 'Desktop')return 1;
        if(typeName == 'SPX Linux')return 2;
        if(typeName == 'Image Manager')return 7;
        if(typeName == 'Server')return 2;
        return null;
    }
    public static Integer languageNumFromName(String Lang)
    {
        //system.debug('in languageNumFromName(): Lang :  '+Lang);
        for(Languages__c l : Languages__c.getAll().values())//(name of custom setting  variableName : name of custom setting.getAll().values()
        {
            if(l.Name == lang){//if(variableName. name of setting to check == variableName passed in)
                //system.debug(l.Number__c);
                return (Integer)l.Number__c; // return variablename.setting you want to output;
            }
        }
        return 0;
    }

}