mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionTypesAsText__c</fullName>
        <description>This is a text version of the Multi-Picklist transactionTypes__c field that can be used in formulae. It is not intended to be displayed or updated directly.</description>
        <label>Transaction Types (text)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionTypes__c</fullName>
        <inlineHelpText>Some of the Transaction Types will be automatically managed depending on any Agreements in place</inlineHelpText>
        <label>Transaction Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>transactionTypes</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Agreement__c.object
<CustomObject>
    <description>Account accepted agreements.</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>The account related to this agreement</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>What type of agreement is this?</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>Master MSP</fullName>
                </value>
                <value>
                    <fullName>MSP</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>STCA-{YYYY}{MM}{0000}</displayFormat>
        <label>Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/triggerDisablement__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will control Trigger disablement at a global level (SSF-528). This requires that a Trigger conforms to the new Trigger framework (SSF-330).</description>
    <fields>
        <fullName>isDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether the trigger is disabled or not</description>
        <label>Is disabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Disablement</label>
</CustomObject>

globalValueSets/transactionTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Business User</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>Country Partner</label>
    </customValue>
    <customValue>
        <fullName>Direct Market Reseller (DMR)</fullName>
    </customValue>
    <customValue>
        <fullName>Distribution Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors Partner Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Home User</fullName>
    </customValue>
    <customValue>
        <fullName>International Master Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Service Provider (MSP)</fullName>
    </customValue>
    <customValue>
        <fullName>Original Equipment Manufacturer (OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Press / Media Evaluator</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Trial User</fullName>
    </customValue>
    <customValue>
        <fullName>Value Added Reseller (VAR)</fullName>
    </customValue>
    <description>Formerly User Type fields that occurs on Account, Lead and Contacts</description>
    <masterLabel>Transaction Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/classes/AgreementTriggerHandler.cls
/**
  \file         AgreementTriggerHandler.cls
  \brief        This class will implement a trigger handler for the Agreement__c custom object
  \details      JIRA ticket(s): SSF-115
  \author       Matt Thompson-Moltzen
  \version      1.5
  \date         30 August 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1     2017-07-28  Matt Thompson-Moltzen     Update the user type on adding/deleting an agreement (SF-399).
  1.2     2017-08-14  Matt Thompson-Moltzen     Call the Accounts class setTransactionTypes() member function after inserting/updating/deleting an agreement (SSF-399).
  1.3     2017-08-22  Matt Thompson-Moltzen     Added disabled trigger functionality (SSF-528).
  1.4     2017-08-24  Matt Thompson-Moltzen     Agreement type 'VAR' is now deprecated and replaced by 'Reseller' (SSF-533).
  1.5     2017-08-30  Matt Thompson-Moltzen     Changed references to User_Type__c to transactionTypesAsText__c (SSF-458).
  1.6     2017-09-11  Matt Thompson-Moltzen     Stop generating cases when a contract (agreement) is signed (SSF-609).
*/
public with sharing class AgreementTriggerHandler implements TriggerSingularInterface
{
  //
  // variables
  //
  private Set<Id> acctIds = new Set<Id>();

  private static Boolean isDisabled = false;

  public static void disableTrigger()
  {
    isDisabled = true;
  }

  public static void enableTrigger()
  {
    isDisabled = false;
  }

	//
  // constructor
  //
  public AgreementTriggerHandler()
  {
  }

  public Boolean isDisabled()
  {
    triggerDisablement__c td = triggerDisablement__c.getInstance('agreementTrigger');

    if      (td == null)               { return isDisabled; }
    else if (td.isDisabled__c == true) { return true; }
    else                               { return isDisabled; }
  }

  //
 	// member functions/methods - define all methods from the interface even if not used
  //
  public void preBeforeOperations()
  {
  }

  public void beforeInsert(SObject newObject)
  {
  }

  public void beforeUpdate(SObject oldObject, SObject newObject)
  {
  }

  public void beforeDelete(SObject oldObject)
  {
  }

  public void preAfterOperations()
  {
  }

  public void afterInsert(SObject newObject)
  {
  	Agreement__c agt = (Agreement__c)newObject;
/*
  	Integer nAgreements = [SELECT COUNT() FROM Agreement__c WHERE (Account__c = :agt.Account__c) AND (Type__c IN ('Cloud', 'MSP', 'Reseller', 'VAR'))];

    if (nAgreements == 1) {                                                     // this is the first agreement
      Agreements agts = new Agreements();

      agts.sendEmail(agt);
      agts.createCase(agt);
    }
*/
    acctIds.add(agt.Account__c);
  }

  public void afterUpdate(SObject oldObject, SObject newObject)
  {
    Agreement__c agt = (Agreement__c)newObject;

    acctIds.add(agt.Account__c);
  }

  public void afterDelete(SObject oldObject)
  {
    Agreement__c agt = (Agreement__c)oldObject;

    acctIds.add(agt.Account__c);
  }

  public void postOperations()
  {
    //
    // update all Account objects that had an Agreement inserted/updated/deleted
    //
    List<Account> accts = [SELECT Id, transactionTypes__c FROM Account WHERE (Id IN :acctIds)];

    if (accts.isEmpty() == false) {
      try {
        update accts;
      }
      catch (DMLException e) {
        System.debug(LoggingLevel.ERROR, 'AgreementTriggerHandler::postOperations() failed: unable to update Account objects: '  + e.getMessage());
      }
    }
  }

}