mdapi/objects/Account.object
<CustomObject>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>This field will now only be populated by the Lead conversion process and it is therefore only valid to reference it on an INSERT of an Account object where it will initially set the transactionTypes__c field (SSF-458). At all other times, the transactionTypes__c/transactionTypesAsText__c fields should be used.</description>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>International Master Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionTypes__c</fullName>
        <inlineHelpText>Some of the Transaction Types will be automatically managed depending on any Agreements in place</inlineHelpText>
        <label>Transaction Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>transactionTypes</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/transactionTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alliance Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Business User</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CP</fullName>
        <label>Country Partner</label>
    </customValue>
    <customValue>
        <fullName>Direct Market Reseller (DMR)</fullName>
    </customValue>
    <customValue>
        <fullName>Distribution Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors Partner Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>Home User</fullName>
    </customValue>
    <customValue>
        <fullName>International Master Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Managed Service Provider (MSP)</fullName>
    </customValue>
    <customValue>
        <fullName>Original Equipment Manufacturer (OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <default>true</default>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Press / Media Evaluator</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic</fullName>
    </customValue>
    <customValue>
        <fullName>Trial User</fullName>
    </customValue>
    <customValue>
        <fullName>Value Added Reseller (VAR)</fullName>
    </customValue>
    <description>Formerly User Type fields that occurs on Account, Lead and Contacts</description>
    <masterLabel>Transaction Types</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

mdapi/classes/AccountsTest.cls
/**
  \file         AccountsTest.cls
  \brief        Test class for the Accounts class
  \details
  \author       Matt Thompson-Moltzen
  \version      1.1
  \date         7 September 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
  \par Change Log
  Version   Date        Author                  Description
  1.1				2017-09-07	Matt Thompson-Moltzen		Specified a value for User_Type__c when creating Account.
*/
@isTest (SeeAllData = true)
private class AccountsTest
{
  static testMethod void accountsTest1()
  {
    Account a = new Account();

    a.Name              ='STC';
    a.Type              ='Prospect';
    a.BillingCity       ='Sydney';
    a.BillingState      ='NSW';
    a.BillingPostalCode ='2000';
    a.BillingCountry    ='AU';

    a.User_Type__c        = 'Business User';
//    a.transactionTypes__c = 'Business User';

    try {
      insert a;
    }
    catch (Exception e) {
      System.debug('Account::insert() failed: ' + e.getMessage());
    }

    a = [SELECT Id, Name, Type FROM Account WHERE (Id = :a.Id)];

    System.assertEquals('Prospect', a.Type);

    a.AccountNumber = '666444';

    try {
      update a;
    }
    catch (exception e) {
      System.debug('Account::update() failed: ' + e.getMessage());
    }

    a = [SELECT Id, Name, Type FROM Account WHERE (Id = :a.Id)];

    System.assertEquals('Account', a.Type);
  }

  static testMethod void accountsTest2()
  {
    Account a = new Account();

    a.Name              ='STC';
    a.AccountNumber     ='666444';
    a.Type              ='Prospect';
    a.BillingCity       ='Sydney';
    a.BillingState      ='NSW';
    a.BillingPostalCode ='2000';
    a.BillingCountry    ='AU';

    a.User_Type__c        = 'Business User';
//    a.transactionTypes__c = 'Business User';

    try {
      insert a;
    }
    catch (Exception e) {
      System.debug('Account::insert() failed: ' + e.getMessage());
    }

    a = [SELECT Id, Name, Type FROM Account WHERE (Id = :a.Id)];

    System.assertEquals('Account', a.Type);

    a.AccountNumber = null;

    try {
      update a;
    }
    catch (exception e) {
      System.debug('Account::update() failed: ' + e.getMessage());
    }

    a = [SELECT Id, Name, Type FROM Account WHERE (Id = :a.Id)];

    System.assertEquals('Prospect', a.Type);
  }


  static testMethod void testUpdatePartnerPortal()
  {

    String url      = 'http://api.salesforce.com/foo/bar';
    String body     = 'body: body of request';
    String username = 'foo';
    String password = 'bar';

    Accounts.updatePartnerPortal(url, body, username, password);
  }

}