mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Serial_Number_Details__c</fullName>
        <label>Serial Number Details</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number or Account/Machine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/classes/LiveSerialInfoExt.cls
public class LiveSerialInfoExt {
    public final Case c;
    public String liveDetails {get;set;}
    public String storedDetails {get;set;}
    public Boolean shouldRefresh {get;set;}
    public String redirectUrl {get;set;}
    public LiveSerialInfoExt(ApexPages.StandardController ctrl){
        liveDetails = '';
        storedDetails = '';
        c = (Case)ctrl.getRecord();
        if(c.Serial_Number__c == null)
            return;

        liveDetails = formatText(SerialNumberSupportInfo.getSNInfo(c.Serial_Number__c));
        storedDetails = formatText(c.Serial_Number_Details__c);
        
    }
    
    private String formatText(String text){
        if(text == null)
            return text;
        return text.trim().replaceAll('\n','<br/>');
    }
}