mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assistance_Type__c</fullName>
        <label>Assistance Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Select_User_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Licensing Assistance</fullName>
                </value>
                <value>
                    <fullName>Technical Assistance</fullName>
                </value>
                <value>
                    <fullName>Sales Assistance</fullName>
                </value>
                <value>
                    <fullName>Product_Return</fullName>
                    <label>Product Return / RMA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select_User_Type__c</fullName>
        <label>User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial User</fullName>
                </value>
                <value>
                    <fullName>Home User</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Managed Service Provider (MSP)</fullName>
                </value>
                <value>
                    <fullName>Value Added Reseller (VAR)</fullName>
                </value>
                <value>
                    <fullName>Both MSP and VAR</fullName>
                </value>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Original Equipment Manufacturer (OEM)</fullName>
                </value>
                <value>
                    <fullName>Direct Market Reseller (DMR)</fullName>
                </value>
                <value>
                    <fullName>Press / Media Evaluator</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Distributors Partner Reseller</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <label>Country Partner</label>
                </value>
                <value>
                    <fullName>Distribution Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Serial_Number_Details__c</fullName>
        <label>Serial Number Details</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number or Account/Machine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alaska Time (2 hours behind)</fullName>
                </value>
                <value>
                    <fullName>Atlantic Time (3 hours ahead)</fullName>
                </value>
                <value>
                    <fullName>Central Time (1 hour ahead)</fullName>
                </value>
                <value>
                    <fullName>Eastern Time (2 hours ahead)</fullName>
                </value>
                <value>
                    <fullName>Hawaii Time (4 hours behind)</fullName>
                </value>
                <value>
                    <fullName>Mountain Time (Current Time)</fullName>
                </value>
                <value>
                    <fullName>Newfoundland Time (3.5 hours ahead)</fullName>
                </value>
                <value>
                    <fullName>Pacific Time (1 hour behind)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licenses (Account)</relationshipLabel>
        <relationshipName>Licensing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration__c</fullName>
        <inlineHelpText>Key Expiration</inlineHelpText>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>License Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Product Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/classes/InboundLicenseUpdateTest.cls
@IsTest
private class InboundLicenseUpdateTest{

    private static final String TODAYS_DATE = String.valueOf(Date.today());
    private static final String VALID_KEY = '421D-D2E0-74AA-AB04';
    private static final String EXIRED_KEY = 'ABF9-CA32-8720-E1BA';
    private static final String CASE_STATUS_IN_PROGRESS = 'In Progress';
    private static final String CASE_STATUS_WAITING_RENEWAL = 'Waiting for Renewal';
    private static final String CASE_SERIAL_NUMBER_DETAILS = 'Renewed in AU';
    private static final String LICENSE_STATUS_ACTIVE = 'Active';
    private static final String BASE_URL = URL.getSalesforceBaseUrl().toExternalForm();

    @testSetup static void testDataSetup() {
        Account testAccount = new Account(Name = 'testAccount');
        insert testAccount;

        Contact testContact = new Contact(LastName = 'testContact');
        insert testContact;

        List<License__c> testLicenses = new List<License__c>();
        License__c validLicense = new License__c(Name = VALID_KEY,
                                                    Account__c = testAccount.Id);
        testLicenses.add(validLicense);
        License__c expiredLicense = new License__c(Name = EXIRED_KEY,
                                                    Account__c = testAccount.Id,
                                                    Status__c = 'Inactive');
        testLicenses.add(expiredLicense);
        insert testLicenses;

        List<Case> testCases = new List<Case>();
        Case validKeyCase = new Case(ContactId = testContact.Id,
                                 Time_Zone__c = 'Alaska Time (2 hours behind)',
                                 Select_User_Type__c = 'Home User',
                                 Assistance_Type__c = 'Licensing Assistance',
                                 Status = CASE_STATUS_WAITING_RENEWAL,
                                 Serial_Number__c = VALID_KEY);

         testCases.add(validKeyCase);
         Case invalidKeyCase = new Case(ContactId = testContact.Id,
                                  Time_Zone__c = 'Alaska Time (2 hours behind)',
                                  Select_User_Type__c = 'Home User',
                                  Assistance_Type__c = 'Licensing Assistance',
                                  Status = CASE_STATUS_WAITING_RENEWAL,
                                  Serial_Number__c = EXIRED_KEY);
        testCases.add(invalidKeyCase);
        insert testCases;
    }

    // Test with Valid License Key
    @isTest static void testValidLicense(){

            RestRequest req = new RestRequest();
            RestResponse res = new RestResponse();

            req.requestURI = BASE_URL+'/services/apexrest/LicenseUpdate';
            req.httpMethod = 'POST';
            req.requestBody  = Blob.valueof('<sf:Product_Key_v4__c>'+VALID_KEY+'</sf:Product_Key_v4__c> <sf:Renewal_Date__c>'+TODAYS_DATE+'</sf:Renewal_Date__c> <sf:Status__c>Active</sf:Status__c>');

            RestContext.request = req;
            RestContext.response = res;

            InboundLicenseUpdate.updateLicensesAndCases();

            List<License__c> assertLicenses = [SELECT Expiration__c,Status__c
                                                FROM License__c
                                                WHERE Name = :VALID_KEY];
            for(License__c objLicense : assertLicenses){
                System.assertEquals(LICENSE_STATUS_ACTIVE, objLicense.Status__c);
                System.assertEquals(Date.today() ,objLicense.Expiration__c);
            }

            List<Case> assertCases = [SELECT Serial_Number_Details__c,Status
                                        FROM Case
                                        WHERE Serial_Number__c = :VALID_KEY
                                        AND Status = :CASE_STATUS_WAITING_RENEWAL];
            for(Case objCase : assertCases){
                System.assertEquals(CASE_SERIAL_NUMBER_DETAILS ,objCase.Serial_Number_Details__c);
                System.assertEquals(CASE_STATUS_IN_PROGRESS ,objCase.Status);
            }
    }

    // Test with Invalid License Key
    @isTest static void testInvalidLicense(){

            RestRequest req = new RestRequest();
            RestResponse res = new RestResponse();

            req.requestURI = BASE_URL+'/services/apexrest/LicenseUpdate';
            req.httpMethod = 'POST';
            req.requestBody  = Blob.valueof('<sf:Product_Key_v4__c>'+EXIRED_KEY+'</sf:Product_Key_v4__c> <sf:Renewal_Date__c>'+TODAYS_DATE+'</sf:Renewal_Date__c> <sf:Status__c>Active</sf:Status__c>');

            RestContext.request = req;
            RestContext.response = res;

            InboundLicenseUpdate.updateLicensesAndCases();

            List<License__c> assertLicenses = [SELECT Expiration__c,Status__c
                                                FROM License__c
                                                WHERE Name = :EXIRED_KEY];
            for(License__c objLicense : assertLicenses){
                System.assertEquals(LICENSE_STATUS_ACTIVE, objLicense.Status__c);
                System.assertEquals(Date.today() ,objLicense.Expiration__c);
            }

            List<Case> assertCases = [SELECT Serial_Number_Details__c,Status
                                        FROM Case
                                        WHERE Serial_Number__c = :EXIRED_KEY
                                        AND Status = :CASE_STATUS_WAITING_RENEWAL];
            for(Case objCase : assertCases){
                System.assertEquals(CASE_SERIAL_NUMBER_DETAILS ,objCase.Serial_Number_Details__c);
                System.assertEquals(CASE_STATUS_IN_PROGRESS ,objCase.Status);
            }
    }
}