mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Review_Comments__c</fullName>
        <label>Case Review: Comments</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_Review_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Review: Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Review_Escalation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Review: Escalation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Review_General__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Review: General</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Review_Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Review: Information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Review_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Review: Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Review_Serial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Review: Serial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Assistance_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cloud_Backup</fullName>
                    <label>Cloud Backup</label>
                </value>
                <value>
                    <fullName>Cloud_Services</fullName>
                    <label>Cloud Services</label>
                </value>
                <value>
                    <fullName>File_Backup_and_Recovery</fullName>
                    <label>File Backup and Recovery</label>
                </value>
                <value>
                    <fullName>Granular_Recovery_for_Exchange</fullName>
                    <label>Granular Recovery for Exchange</label>
                </value>
                <value>
                    <fullName>ImageManager</fullName>
                </value>
                <value>
                    <fullName>OneBlox</fullName>
                </value>
                <value>
                    <fullName>Recovery_Environments</fullName>
                    <label>Recovery Environments</label>
                </value>
                <value>
                    <fullName>ShadowControl</fullName>
                </value>
                <value>
                    <fullName>ShadowProtect_Linux</fullName>
                    <label>ShadowProtect (Linux)</label>
                </value>
                <value>
                    <fullName>ShadowProtect_Windows</fullName>
                    <label>ShadowProtect (Windows)</label>
                </value>
                <value>
                    <fullName>StorageCraft_Websites</fullName>
                    <label>StorageCraft Websites</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Case_Review__c.object
<CustomObject>
    <description>Capture case reviews performed by Escalation leads</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Reviews</relationshipLabel>
        <relationshipName>Case_Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Escalation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>General__c</fullName>
        <defaultValue>false</defaultValue>
        <label>General</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Serial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Capture status of the case when the review is completed.</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Review</label>
    <nameField>
        <displayFormat>CaseRev-{00000}</displayFormat>
        <label>Case Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Review</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseReviewCapture.cls
public class CaseReviewCapture {
    // These variables store Trigger.oldMap and Trigger.newMap
    Map<Id, Case> oldMap;
    Map<Id, Case> newMap;
    
    // This is the constructor
    // A map of the old and new records is expected as inputs
    public CaseReviewCapture(
        Map<Id, Case> oldTrigger, 
        Map<Id, Case> newTrigger) {
            oldMap = oldTrigger;
            newMap = newTrigger;
        }
    
    // The one method your master trigger will call
    public void RecordReview() {
        // Logic
        List<Case_Review__c> crs = new List<Case_Review__c>();
        List<Case> casesToUpdate = new List<Case>();
        for(Case c: newMap.values()){
            if(caseReviewPerformed(c)){
                crs.add(createReview(c));
                casesToUpdate.add(cleanReview(c));
            }
        }
        
        if(!crs.isEmpty())
            Insert crs;
        
        if(!casesToUpdate.isEmpty())
            Update casesToUpdate;
    }
    
    public Case cleanReview(Case c){
        Case cse = c.clone(true, true, true, true);
        cse.Case_Review_Comments__c = null;
        cse.Case_Review_Contact__c = false;
        cse.Case_Review_Escalation__c = false;
        cse.Case_Review_General__c = false;
        cse.Case_Review_Information__c = false;
        cse.Case_Review_Product__c = false;
        cse.Case_Review_Serial__c = false;
        return cse;
    }
    
    public Case_Review__c createReview(Case c){
        Case_Review__c cr = new Case_Review__c(
            Comments__c = c.Case_Review_Comments__c,
            Contact__c = c.Case_Review_Contact__c,
            Escalation__c = c.Case_Review_Escalation__c,
            General__c = c.Case_Review_General__c,
            Information__c = c.Case_Review_Information__c,
            Product__c = c.Case_Review_Product__c,
            Serial__c = c.Case_Review_Serial__c,
            Case__c = c.Id,
            Status__c = c.Status
        );
        
        // Have to handle when case is owned by queue
        // If owned by queue the don't set owner id
        if(c.OwnerId.getSobjectType() == Schema.User.getSobjectType())
            cr.OwnerId = c.OwnerId;
        return cr;
    }
    
    public Boolean caseReviewPerformed(Case c){
        if(c.Case_Review_Comments__c != null)
            return true;
        if(c.Case_Review_Contact__c)
            return true;
        if(c.Case_Review_Escalation__c)
            return true;
        if(c.Case_Review_General__c)
            return true;
        if(c.Case_Review_Information__c)
            return true;
        if(c.Case_Review_Product__c)
            return true;
        if(c.Case_Review_Serial__c)
            return true;
        // Guess nobody reviewed the case today, moving on with our lives
        return false;
    }
}