mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Version__c</fullName>
        <label>Product Version</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1.0.0</fullName>
                </value>
                <value>
                    <fullName>1.10</fullName>
                </value>
                <value>
                    <fullName>1.8</fullName>
                </value>
                <value>
                    <fullName>1.9</fullName>
                </value>
                <value>
                    <fullName>1.x</fullName>
                </value>
                <value>
                    <fullName>2.0.1.27</fullName>
                </value>
                <value>
                    <fullName>2.0.1.35</fullName>
                </value>
                <value>
                    <fullName>2.1.0</fullName>
                </value>
                <value>
                    <fullName>2.1.1</fullName>
                </value>
                <value>
                    <fullName>2.10</fullName>
                </value>
                <value>
                    <fullName>2.11</fullName>
                </value>
                <value>
                    <fullName>2.12</fullName>
                </value>
                <value>
                    <fullName>2.13</fullName>
                </value>
                <value>
                    <fullName>2.14</fullName>
                </value>
                <value>
                    <fullName>2.14.1</fullName>
                </value>
                <value>
                    <fullName>2.15</fullName>
                </value>
                <value>
                    <fullName>2.15.1</fullName>
                </value>
                <value>
                    <fullName>2.15.2</fullName>
                </value>
                <value>
                    <fullName>2.15.3</fullName>
                </value>
                <value>
                    <fullName>2.15.4</fullName>
                </value>
                <value>
                    <fullName>2.15.5</fullName>
                </value>
                <value>
                    <fullName>2.16</fullName>
                </value>
                <value>
                    <fullName>2.16.1</fullName>
                </value>
                <value>
                    <fullName>2.17</fullName>
                </value>
                <value>
                    <fullName>2.17.1</fullName>
                </value>
                <value>
                    <fullName>2.2.0</fullName>
                </value>
                <value>
                    <fullName>2.2.2</fullName>
                </value>
                <value>
                    <fullName>2.2.4</fullName>
                </value>
                <value>
                    <fullName>2.3.0</fullName>
                </value>
                <value>
                    <fullName>2.5.1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Assistance_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cloud_Backup</fullName>
                    <label>Cloud Backup</label>
                </value>
                <value>
                    <fullName>Cloud_Services</fullName>
                    <label>Cloud Services</label>
                </value>
                <value>
                    <fullName>File_Backup_and_Recovery</fullName>
                    <label>File Backup and Recovery</label>
                </value>
                <value>
                    <fullName>Granular_Recovery_for_Exchange</fullName>
                    <label>Granular Recovery for Exchange</label>
                </value>
                <value>
                    <fullName>ImageManager</fullName>
                </value>
                <value>
                    <fullName>OneBlox</fullName>
                </value>
                <value>
                    <fullName>Recovery_Environments</fullName>
                    <label>Recovery Environments</label>
                </value>
                <value>
                    <fullName>ShadowControl</fullName>
                </value>
                <value>
                    <fullName>ShadowProtect_Linux</fullName>
                    <label>ShadowProtect (Linux)</label>
                </value>
                <value>
                    <fullName>ShadowProtect_Windows</fullName>
                    <label>ShadowProtect (Windows)</label>
                </value>
                <value>
                    <fullName>StorageCraft_Websites</fullName>
                    <label>StorageCraft Websites</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <fields>
        <fullName>Default_Data_Category__c</fullName>
        <inlineHelpText>Optional - Enter the Product Data Category API name to be used as a default for new articles in this guide.  Examples:  ShadowControl, Cloud_Services</inlineHelpText>
        <label>Default Data Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/Troubleshooting__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Troubleshooting Articles</description>
    <fields>
        <fullName>Cause__c</fullName>
        <description>Describe the cause of the issue, include screenshot if needed, but also include text contained in screenshot.</description>
        <label>Cause</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <description>Troubleshooting Problem Description</description>
        <label>Problem</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product_Versions__c</fullName>
        <description>List of products and exact versions or ranges of versions where this message can be seen.
Example:  ShadowProtect SPX (Windows) - All</description>
        <inlineHelpText>List of products and exact versions or ranges of versions where this message can be seen.
Example:  ShadowProtect SPX (Windows) - All</inlineHelpText>
        <label>Product Versions Affected</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <description>Resolution steps and recommendations for the issue</description>
        <label>Resolution</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Troubleshooting</label>
    <pluralLabel>Troubleshooting</pluralLabel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/AgentContributionArticleController.cls
public class AgentContributionArticleController {
    // The constructor must take a ApexPages.KnowledgeArticleVersionStandardController as an argument
    public AgentContributionArticleController(ApexPages.KnowledgeArticleVersionStandardController ctl) {
        SObject article = ctl.getRecord();   //this is the SObject for the new article. 
                                             //It can optionally be cast to the proper article type, e.g. FAQ__kav article = (FAQ__kav) ctl.getRecord();
        // System.debug(ApexPages.currentPage().getParameters());
        if (article instanceof User_Guide__kav ){
            User_Guide__kav userguide = (User_Guide__kav)article;
            String guideId = ApexPages.currentPage().getParameters().get('guideId');
            userguide.Guide__c = guideId;
            userguide.title = '';           
            List<Guide__c> DataQuery = [select Default_Data_Category__c from Guide__c where Id=:guideId];
            ctl.selectDataCategory('Products',DataQuery[0].Default_Data_Category__c);
            return;
        }
        
        String sourceId = ctl.getSourceId(); //this returns the id of the case that was closed.
        Case c = [select subject, description, Cause__c, Resolution__c, Product__c, Product_Version__c from Case where id=:sourceId];
        
        article.put('title',c.subject);  //this overrides the default behavior of pre-filling the title of the article with the subject of the closed case. 
        article.put('summary',c.description);
        String Product = c.Product__c;
        String ProductVer = c.Product_Version__c;
        if(String.isBlank(ProductVer)){
        ProductVer = '- All';
        }
        String ProductName = Product.replace('_', ' ');
        String ProductVersions = ProductName + ' ' + ProductVer;
        article.put('Product_Versions__c',ProductVersions);
        Product = Product.replace(' ', '_');
        ctl.selectDataCategory('Products',Product);  //Only one category per category group can be specified.

        if (article instanceof Troubleshooting__kav){
        article.put('Problem__c',c.description);  
        article.put('Cause__c',c.Cause__c);  
        article.put('Resolution__c',c.Resolution__c);  
        }

    }
  }