mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Serial_Number_Details__c</fullName>
        <label>Serial Number Details</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number or Account/Machine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/classes/CaseSerialDetailCapture.cls
global class CaseSerialDetailCapture implements Queueable, Database.AllowsCallouts {

    public Case cse;

    public CaseSerialDetailCapture(Case c){
        cse = c;
    }

    public void execute(QueueableContext context) {
    	updateLicenseDetails(cse.Id);
    }

    webservice static void updateLicenseDetails(Id cid){
        Case c = [select Id, Serial_Number__c from Case where Id = :cid];
        if(c.Serial_Number__c != null){
            c.Serial_Number_Details__c = SerialNumberSupportInfo.getSNInfo(c.Serial_Number__c);
            System.debug('Details:'+c.Serial_Number_Details__c);
            if(c.Serial_Number_Details__c != null)
            	update c;
        }
    }
}