mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product_Version__c</fullName>
        <label>Product Version</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1.0.0</fullName>
                </value>
                <value>
                    <fullName>1.10</fullName>
                </value>
                <value>
                    <fullName>1.8</fullName>
                </value>
                <value>
                    <fullName>1.9</fullName>
                </value>
                <value>
                    <fullName>1.x</fullName>
                </value>
                <value>
                    <fullName>2.0.1.27</fullName>
                </value>
                <value>
                    <fullName>2.0.1.35</fullName>
                </value>
                <value>
                    <fullName>2.1.0</fullName>
                </value>
                <value>
                    <fullName>2.1.1</fullName>
                </value>
                <value>
                    <fullName>2.10</fullName>
                </value>
                <value>
                    <fullName>2.11</fullName>
                </value>
                <value>
                    <fullName>2.12</fullName>
                </value>
                <value>
                    <fullName>2.13</fullName>
                </value>
                <value>
                    <fullName>2.14</fullName>
                </value>
                <value>
                    <fullName>2.14.1</fullName>
                </value>
                <value>
                    <fullName>2.15</fullName>
                </value>
                <value>
                    <fullName>2.15.1</fullName>
                </value>
                <value>
                    <fullName>2.15.2</fullName>
                </value>
                <value>
                    <fullName>2.15.3</fullName>
                </value>
                <value>
                    <fullName>2.15.4</fullName>
                </value>
                <value>
                    <fullName>2.15.5</fullName>
                </value>
                <value>
                    <fullName>2.16</fullName>
                </value>
                <value>
                    <fullName>2.16.1</fullName>
                </value>
                <value>
                    <fullName>2.17</fullName>
                </value>
                <value>
                    <fullName>2.17.1</fullName>
                </value>
                <value>
                    <fullName>2.2.0</fullName>
                </value>
                <value>
                    <fullName>2.2.2</fullName>
                </value>
                <value>
                    <fullName>2.2.4</fullName>
                </value>
                <value>
                    <fullName>2.3.0</fullName>
                </value>
                <value>
                    <fullName>2.5.1</fullName>
                </value>
                <value>
                    <fullName>Previous Version</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Assistance_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cloud_Backup</fullName>
                    <label>Cloud Backup</label>
                </value>
                <value>
                    <fullName>Cloud_Services</fullName>
                    <label>Cloud Services</label>
                </value>
                <value>
                    <fullName>File_Backup_and_Recovery</fullName>
                    <label>File Backup and Recovery</label>
                </value>
                <value>
                    <fullName>Granular_Recovery_for_Exchange</fullName>
                    <label>Granular Recovery for Exchange</label>
                </value>
                <value>
                    <fullName>ImageManager</fullName>
                </value>
                <value>
                    <fullName>OneBlox</fullName>
                </value>
                <value>
                    <fullName>Recovery_Environments</fullName>
                    <label>Recovery Environments</label>
                </value>
                <value>
                    <fullName>ShadowControl</fullName>
                </value>
                <value>
                    <fullName>ShadowProtect_Linux</fullName>
                    <label>ShadowProtect (Linux)</label>
                </value>
                <value>
                    <fullName>ShadowProtect_Windows</fullName>
                    <label>ShadowProtect (Windows)</label>
                </value>
                <value>
                    <fullName>StorageCraft_Websites</fullName>
                    <label>StorageCraft Websites</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/Troubleshooting__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Troubleshooting Articles</description>
    <fields>
        <fullName>Product_Versions__c</fullName>
        <description>List of products and exact versions or ranges of versions where this message can be seen.
Example:  ShadowProtect SPX (Windows) - All</description>
        <inlineHelpText>List of products and exact versions or ranges of versions where this message can be seen.
Example:  ShadowProtect SPX (Windows) - All</inlineHelpText>
        <label>Product Versions Affected</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Troubleshooting</label>
    <pluralLabel>Troubleshooting</pluralLabel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/AgentContributionArticleControllerTest.cls
@isTest(SeeAllData=true)
private class AgentContributionArticleControllerTest {
    static testMethod void testAgentContributionArticleController() {
         String caseSubject = 'Test Subject';
         String caseDesc = 'Test Case Description';
         String caseProduct = 'ShadowControl';
         String caseProductVer = 'Previous Version';
         String ProductVer = '- All';
                
         Case c = new Case();
         c.subject= caseSubject;
         c.description = caseDesc;
         c.Product__c = caseProduct;
         c.Product_Version__c = caseProductVer;
         insert c;
         String caseId = c.id;
         System.debug('Created Case: ' + caseId);

         ApexPages.currentPage().getParameters().put('sourceId', caseId);
         ApexPages.currentPage().getParameters().put('sfdc.override', '1');
        
         ApexPages.KnowledgeArticleVersionStandardController ctl =
            new ApexPages.KnowledgeArticleVersionStandardController(new Troubleshooting__kav());

         new AgentContributionArticleController(ctl);
 
         System.assertEquals(caseId, ctl.getSourceId());
         System.assertEquals(caseSubject, ctl.getRecord().get('title'));
         System.assertEquals(caseDesc, ctl.getRecord().get('summary'));
         System.assertEquals(caseProduct + ' ' + caseProductVer, ctl.getRecord().get('Product_Versions__c'));
    }
    
        static testMethod void testAgentUserGuideType() {
         String caseSubject = 'Test Subject';
         String caseDesc = 'Test Case Description';
         String caseProduct = 'ShadowControl';
         String caseProductVer = 'Previous Version';
         String ProductVer = '- All';
//         Id gId = 'a0xc0000002E7Sl';
         Id gId = [SELECT id from Guide__c LIMIT 1].Id;

        
         Case c = new Case();
         c.subject= caseSubject;
         c.description = caseDesc;
         c.Product__c = caseProduct;
         c.Product_Version__c = caseProductVer;
         insert c;
         String caseId = c.id;
         System.debug('Created Case: ' + caseId);

         ApexPages.currentPage().getParameters().put('sourceId', caseId);
         ApexPages.currentPage().getParameters().put('sfdc.override', '1');
         ApexPages.currentPage().getParameters().put('guideId', gId);
        
         ApexPages.KnowledgeArticleVersionStandardController usr =
            new ApexPages.KnowledgeArticleVersionStandardController(new User_Guide__kav());

         new AgentContributionArticleController(usr);
 
         System.assertEquals(caseId, usr.getSourceId());
         //System.assertEquals(caseSubject, usr.getRecord().get('title'));
         //System.assertEquals(caseDesc, usr.getRecord().get('summary'));
         //System.assertEquals(caseProduct + ' ' + caseProductVer, usr.getRecord().get('Product_Versions__c'));
         System.assertEquals(gId, usr.getRecord().get('Guide__c'));
   }

}