mdapi/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Owner_Name__c</fullName>
        <formula>BLANKVALUE(Owner:Queue.QueueName, Owner:User.FirstName+&quot; &quot;+ Owner:User.LastName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Needs_Emergency_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to trigger workflow rules to remind staff about unclaimed emergency case.</description>
        <label>Needs Emergency Reminder</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapi/classes/CaseEmergencyTriggerEmail.cls
public class CaseEmergencyTriggerEmail implements CaseEmergencyScheduled.IScheduleDispatched {
    public void execute(SchedulableContext sc){
        List<Case> cases = [select id from case where Case_Owner_Name__c LIKE '%Emergency%' AND Needs_Emergency_Reminder__c = false AND IsClosed = false];
        for(Case c: cases){
            c.Needs_Emergency_Reminder__c = true;
        }
        Update cases;
    }
}