mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>LeadOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrphanedLead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orphaned Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>OrphanedContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/Generic_Email_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to prevent account lookup for generic email domains.</description>
    <label>Generic Email List</label>
</CustomObject>

mdapi/classes/contactAfterInsertAfterUpdateTest.cls
@isTest
private class contactAfterInsertAfterUpdateTest {

	@isTest static void test_method_one() {
		// Totally Orphaned
		Contact c = new contact(lastname = 'lastname', email = 'email@website.com');
		insert c;
        c = [Select Id, AccountId, Status__c from Contact where Id = :c.Id];
        Account acct = [select id from account where name = 'DO NOT DELETE: ORPHAN ACCOUNT' limit 1];
        
        System.assertEquals(acct.Id, c.AccountId);
        System.assertEquals('Orphaned', c.Status__c);
	}
	@isTest static void test_method_two() {
		// Account
		account a = new account(name = 'name', website = 'website.com');
		insert a;
		Contact c = new contact(lastname = 'lastname', email = 'email@website.com');
		insert c;
        c = [Select Id, AccountId from Contact where Id = :c.Id];
        System.assertEquals(a.Id, c.AccountId);
	}

	@isTest static void test_method_three() {
		lead l = new lead(company = 'company', email = 'email@website.com', lastname = 'lastname', OwnerId = UserInfo.getUserId());
		insert l;
		Contact c = new contact(lastname = 'lastname', email = 'email@website.com');
		insert c;
        c = [Select Id, AccountId, OrphanedLead__c, LeadOwner__c from Contact where Id = :c.Id];
        Account acct = [select id from account where name = 'DO NOT DELETE: ORPHAN ACCOUNT' limit 1];
        
        System.assertEquals(acct.Id, c.AccountId);
        System.assertEquals(l.Id, c.OrphanedLead__c);
        System.assertEquals(UserInfo.getUserId(), c.LeadOwner__c);
	}

	@isTest static void test_method_blockemail() {
        List<Generic_Email_List__c> gel = new List<Generic_Email_List__c>();
        gel.add(new Generic_Email_List__c(Name = 'website.com'));
        Insert gel;
        
		account a = new account(name = 'name', website = 'website.com');
		insert a;
		
        Contact c = new contact(lastname = 'lastname', email = 'email@website.com');
		insert c;
        
        Account acct = [select id from account where name = 'DO NOT DELETE: ORPHAN ACCOUNT' limit 1];
        c = [Select Id, AccountId, Status__c from Contact where Id = :c.Id];
        System.assertEquals(acct.Id, c.AccountId);
	}

}