mdapi/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>LeadOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrphanedLead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orphaned Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>OrphanedContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Orphaned</fullName>
                </value>
                <value>
                    <fullName>Left The Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Country_ISO_Map__c.object
<CustomObject>
    <description>JIRA SSF-62: this object maps full country names to the ISO 3166-1 alpha-2 (two letter) codes and alpha-3 (three letter) codes for the country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/Generic_Email_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to prevent account lookup for generic email domains.</description>
    <label>Generic Email List</label>
</CustomObject>

mdapi/classes/ContactOrphanedHandlerTest.cls
@isTest
private class ContactOrphanedHandlerTest {

    @isTest static void test_method_one() {
        // Totally Orphaned
        // List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        
        Contact c = new contact(lastname = 'lastname', MailingCountry = 'US', MailingState = 'UT',MailingPostalCode='55555');
        insert c;
        c = [Select Id, AccountId, Status__c from Contact where Id = :c.Id];
        Account acct = [select id from account where name = 'DO NOT DELETE: ORPHAN ACCOUNT' limit 1];

        System.assertEquals(acct.Id, c.AccountId);
        System.assertEquals('Orphaned', c.Status__c);
    }

    @isTest static void test_method_two() {
        // Account
        // List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        
        account a = new account(name = 'name', website = 'website.com', BillingCountry = 'US', BillingState = 'UT',BillingPostalCode='55555');
        insert a;
        Contact c = new contact(lastname = 'lastname', email = 'email@website.com', MailingCountry = 'US', MailingState = 'UT',MailingPostalCode='55555');
        insert c;
        c = [Select Id, AccountId from Contact where Id = :c.Id];
        System.assertEquals(a.Id, c.AccountId);
    }

    @isTest static void test_method_three() {
        // List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        lead l = new lead(company = 'company', email = 'email@website.com', lastname = 'lastname', leadsource='Web', OwnerId = UserInfo.getUserId(),Country = 'AF');
        insert l;
        Contact c = new contact(lastname = 'lastname', email = 'email@website.com',  MailingCountry = 'US', MailingState = 'UT',MailingPostalCode='55555');
        insert c;
        c = [Select Id, AccountId, OrphanedLead__c, LeadOwner__c from Contact where Id = :c.Id];
        Account acct = [select id from account where name = 'DO NOT DELETE: ORPHAN ACCOUNT' limit 1];

        System.assertEquals(acct.Id, c.AccountId);
        System.assertEquals(l.Id, c.OrphanedLead__c);
        System.assertEquals(UserInfo.getUserId(), c.LeadOwner__c);
    }

    @isTest static void test_method_blockemail() {

        // List<SObject> lstCountry = Test.loadData(Country_ISO_Map__c.sObjectType, 'CPQ_Country_ISO_Map');

        
        List<Generic_Email_List__c> gel = new List<Generic_Email_List__c>();
        gel.add(new Generic_Email_List__c(Name = 'website.com'));
        Insert gel;

        account a = new account(name = 'name', website = 'website.com', BillingCountry = 'US', BillingState = 'UT',BillingPostalCode='55555');
        insert a;

        Contact c = new contact(lastname = 'lastname', email = 'email@website.com', MailingCountry = 'US', MailingState = 'UT',MailingPostalCode='55555');
        insert c;

        Account acct = [select id from account where name = 'DO NOT DELETE: ORPHAN ACCOUNT' limit 1];
        c = [Select Id, AccountId, Status__c from Contact where Id = :c.Id];
        System.assertEquals(acct.Id, c.AccountId);
    }

}