mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Formula for link to the Guide in the Community</description>
        <formula>&quot;/support/s/guide/&quot;&amp;Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula for link to the Guide in the Community</inlineHelpText>
        <label>Community URL src=</label>
        <type>Text</type>
    </fields>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Formula field which reflects the correct URL structure needed for community navigation</description>
        <formula>&quot;https://support.storagecraft.com/s/article/&quot;&amp;UrlName</formula>
        <label>Community URL src=</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section Number (examples:  1, 2.4, 3.2.2,  lead with 0 for preface sections)</description>
        <label>Section</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/UserGuideNextPrevController.cls
public class UserGuideNextPrevController {

    @AuraEnabled
    public static User_Guide__kav getNextArticle(String articleId, String lang) {
        List<User_Guide__kav> guides = getSiblings(articleId, lang);
        Boolean found = false;
        for(User_Guide__kav ug : guides){
            // Find the article AFTER the current article
            if(found){
                return ug;
            }
            if(ug.Id == articleId){
                found = true;
            }
        }
        // No articles after our current article
        return new User_Guide__kav();

    }

    @AuraEnabled
    public static User_Guide__kav getPrevArticle(String articleId, String lang) {
        List<User_Guide__kav> guides = getSiblings(articleId, lang);
        Boolean found;
        User_Guide__kav prev = new User_Guide__kav();
        for(User_Guide__kav ug : guides){
            // Find the article BEFORE the current article
            if(ug.Id == articleId){
                return prev;
            }
            prev = ug;
        }
        // just as a catch
        return new User_Guide__kav();
    }

    private static List<User_Guide__kav> getSiblings(String articleId, String lang) {

        // get article's guide id, find other guides
        User_Guide__kav u = [select Id, Guide__c from User_Guide__kav where Id = :articleId];
        if(u.Guide__c == null){
            return new List<User_Guide__kav>();
        }

        Id parentId = u.Guide__c;
//        String query = 'SELECT id, Title, Section__c, Community_URL__c FROM User_Guide__kav WHERE Guide__c = :parentId AND Language = \''+lang+'\'';
        String query = 'SELECT id, Title, Section__c, Community_URL__c FROM User_Guide__kav WHERE Guide__c = \'' + parentId + '\' AND Language = \''+lang+'\'';
        System.debug(query);
        return GuideSectionUtility.sortGuideSections((List<User_Guide__kav>)Database.query(query));
    }
}