mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Landing_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this box is checked the article will be displayed on the user guide landing page</description>
        <inlineHelpText>When this box is checked the article will be displayed as the main link in the user guide list.  The name of this article should be the name of the user guide.</inlineHelpText>
        <label>Landing Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section Number (examples:  1, 2.4, 3.2.2,  lead with 0 for preface sections)</description>
        <label>Section</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/GuideIndexControllerTest.cls
/**
  \file
  \brief        Test Apex controller GuideIndexController
  \details
  \author       Sean Oldoryd
  \version      1.0
  \date         14 Sept 2017
  \copyright    Copyright 2017 StorageCraft Technology Corporation
 */
@IsTest(SeeAllData=true)
public class GuideIndexControllerTest {

    private static Id saProfileIdd = [select id, name from profile where name = 'System Administrator'].Id;
    private static User admin = [select id, name from user where profileid = :saProfileIdd  AND IsActive = true LIMIT 1];

    static void setUpData(){
        String ugkGuideIString = [SELECT Guide__c from User_Guide__kav LIMIT 1].Guide__c;
        User_Guide__kav ugk = new User_Guide__kav(Title='TestIem', Guide__c = ugkGuideIString, Language='en_US', Section__c = '1', urlName = 'testUrlGUID', Landing_Page__c = true);
        test.startTest();
        insert ugk;
        test.stopTest();
    }

    @IsTest public static void testFindAllLandingPages() {
        System.runAs(admin){setUpData();}
        String lang = 'en_US';
        List<User_Guide__kav> ugk = GuideIndexController.findAllLandingPages(lang);

        System.assert(ugk != null);

    }

    @IsTest public static void testGetFieldLabels() {
        System.runAs(admin){setUpData();}
        
        Map<String,String> ugk = GuideIndexController.getFieldLabels();

        System.assert(ugk != null);

    }

}