mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Formula for link to the Guide in the Community</description>
        <formula>&quot;/support/s/guide/&quot;&amp;Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula for link to the Guide in the Community</inlineHelpText>
        <label>Community URL src=</label>
        <type>Text</type>
    </fields>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Formula field which reflects the correct URL structure needed for community navigation</description>
        <formula>&quot;https://support.storagecraft.com/s/article/&quot;&amp;UrlName</formula>
        <label>Community URL src=</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section Number (examples:  1, 2.4, 3.2.2,  lead with 0 for preface sections)</description>
        <label>Section</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/Guide_SectionsController.cls
public class Guide_SectionsController {
    // TODO: Build with field set
    @AuraEnabled
    public static List<User_Guide__kav> findAllForGuide(String guideId, String lang) {
        // get article's guide id, find other guides
        User_Guide__kav u = [select Id, Guide__c from User_Guide__kav where Id = :guideId];
        if(u.Guide__c == null){
            return new List<User_Guide__kav>();
        }
        
        // return GuideSectionUtility.sortGuideSections([SELECT id, Title, Section__c, Community_URL__c FROM User_Guide__kav 
        //                                              WHERE Guide__c = :u.Guide__c AND Language = 'en_US']);
        
        Id parentId = u.Guide__c;
        String query = 'SELECT id, Title, Section__c, Community_URL__c FROM User_Guide__kav WHERE Guide__c = :parentId AND Language = \''+lang+'\'';
        System.debug(query);
        return GuideSectionUtility.sortGuideSections((List<User_Guide__kav>)Database.query(query));
        
    }
    
    private static Map<String, Schema.SObjectField> mapUGFields {get;set;}
    
    // Retrieve the field label for a specific api field
    @AuraEnabled
    public static Map<String, String> getFieldLabels(){
        if(mapUGFields == null){
            mapUGFields = Schema.SobjectType.User_Guide__kav.Fields.getMap();
        }
        
        Map<String, String> fieldLabels = new Map<String, String>();
        for(String field : mapUGFields.keySet()){
            fieldLabels.put(field, mapUGFields.get(field).getDescribe().getLabel());
        }
        return fieldLabels;
    }
    
}