mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Formula for link to the Guide in the Community</description>
        <formula>&quot;/support/s/guide/&quot;&amp;Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula for link to the Guide in the Community</inlineHelpText>
        <label>Community URL src=</label>
        <type>Text</type>
    </fields>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>Community_URL__c</fullName>
        <description>Formula field which reflects the correct URL structure needed for community navigation</description>
        <formula>&quot;https://support.storagecraft.com/s/article/&quot;&amp;UrlName</formula>
        <label>Community URL src=</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Landing_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this box is checked the article will be displayed on the user guide landing page</description>
        <inlineHelpText>When this box is checked the article will be displayed as the main link in the user guide list.  The name of this article should be the name of the user guide.</inlineHelpText>
        <label>Landing Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section Number (examples:  1, 2.4, 3.2.2,  lead with 0 for preface sections)</description>
        <label>Section</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/GuideIndexController.cls
public class GuideIndexController {
    // TODO: Build with field set
    @AuraEnabled
    public static List<User_Guide__kav> findAllLandingPages(String lang) {
        // get article's guide id, find other guides
        String query = 'SELECT id, Title, Section__c, Community_URL__c, Language, Guide__c FROM User_Guide__kav WHERE Landing_Page__c = true AND Language = \''+lang+'\' ORDER BY Title DESC';
        return Database.query(query);
    }
    
    private static Map<String, Schema.SObjectField> mapUGFields {get;set;}
    
    // Retrieve the field label for a specific api field
    @AuraEnabled
    public static Map<String, String> getFieldLabels(){
        if(mapUGFields == null){
            mapUGFields = Schema.SobjectType.User_Guide__kav.Fields.getMap();
        }
        
        Map<String, String> fieldLabels = new Map<String, String>();
        for(String field : mapUGFields.keySet()){
            fieldLabels.put(field, mapUGFields.get(field).getDescribe().getLabel());
        }
        return fieldLabels;
    }
    
}