mdapi/objects/Guide__c.object
<CustomObject>
    <description>Product Documentation - User Guide container for indexing order of articles</description>
    <label>Guide</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guides</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/objects/User_Guide__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Sections for Product Documentation, User Guides, Glossary, ReadMe</description>
    <fields>
        <fullName>ArticleBody__c</fullName>
        <description>Main body of information in the article</description>
        <label>-</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Custom Guide Object</description>
        <label>Guide Name</label>
        <referenceTo>Guide__c</referenceTo>
        <relationshipLabel>Guide Sections</relationshipLabel>
        <relationshipName>User_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section Number (examples:  1, 2.4, 3.2.2,  lead with 0 for preface sections)</description>
        <label>Section</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>User Guide</label>
    <pluralLabel>User Guides</pluralLabel>
</CustomObject>

mdapi/classes/GuidePDFExtension.cls
public class GuidePDFExtension {
    public List<User_Guide__kav> sections {get;set;}
    public GuidePDFExtension(ApexPages.StandardController cont){
        Guide__c g = (Guide__c)cont.getRecord();
        Id gId = g.Id;
        String lang = ApexPages.currentPage().getParameters().get('language');
        if(String.isBlank(lang)){
            lang = 'en_US';
        }
        List<User_Guide__kav> userGuides = Database.query('select Id, Section__c, Title, ArticleBody__c from User_Guide__kav where Guide__c = :gId AND Language = \''+lang+'\'');
        sections = GuideSectionUtility.sortGuideSections(userGuides);
        /* not working correctly
        sections = g.User_Guides__r;
        if(sections == null){
            // sections = new List<User_Guide__kav>();
            return;
        }
        sections = GuideSectionUtility.sortGuideSections(sections);
        g.User_Guides__r.clear();
        g.User_Guides__r.addAll(sections);
		*/
    }
}