mdapi/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product_interested_in__c</fullName>
        <label>Product interested in</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>4312</fullName>
                </value>
                <value>
                    <fullName>5210</fullName>
                </value>
                <value>
                    <fullName>Both 4312 and 5210</fullName>
                </value>
                <value>
                    <fullName>Exablox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>North East</fullName>
                </value>
                <value>
                    <fullName>PacWest</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Federal</fullName>
                </value>
                <value>
                    <fullName>Oceania</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>South Asia</fullName>
                </value>
                <value>
                    <fullName>South East</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>Africa</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Canada - East</fullName>
                </value>
                <value>
                    <fullName>Canada - West</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>South America</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi/classes/LeadS2SHandler.cls
/**
* ===============================================================================================
*   Version     Date              Comment
* ===============================================================================================
*   Initial     3-Mar-2017        - Trigger handler to insert Lead records in connected orgs
*   1.1                           - Code review changes
*/
public with sharing class LeadS2SHandler {

    public static final String STR_EXABLOX_CONNECTION = Label.Exablox_Connection_Name;
    public static final String STR_AU_CONNECTION = Label.AU_Connection_Name;
    public static final String STR_REGION_VALUE = Label.Lead_Region_Value;
    public static final String STR_PRODUCT_INTRESTED_VALUE = Label.Lead_Product_Interested_Value;

    public void insertedLeads(Map<ID,Lead> newLeadMap){
        // Define connection id
        Id networkId1 = ConnectionHelper.getConnectionId(STR_EXABLOX_CONNECTION);
        Id networkId2 = ConnectionHelper.getConnectionId(STR_AU_CONNECTION);

        // only share records created in this org, do not add leads received from another org.
        List<Lead> localAPACRegionLeads = new List<Lead>();
        List<Lead> localProductInterestExabloxLeads = new List<Lead>();
        for (Lead keyLead: newLeadMap.values()) {
            if (keyLead.ConnectionReceivedId == null && String.isNotBlank(keyLead.Region__c) && keyLead.Region__c.equalsIgnoreCase(STR_REGION_VALUE)) { // Hardcoding
                localAPACRegionLeads.add(keyLead);
            }
            if (keyLead.ConnectionReceivedId == null && String.isNotBlank(keyLead.Product_interested_in__c) && keyLead.Product_interested_in__c.containsIgnoreCase(STR_PRODUCT_INTRESTED_VALUE)){
                localProductInterestExabloxLeads.add(keyLead);
            }
        }

        List<PartnerNetworkRecordConnection> leadConnections =  new  List<PartnerNetworkRecordConnection>();

        if (!localAPACRegionLeads.isEmpty()) {
            for (Lead keyLead : localAPACRegionLeads) {
                leadConnections.add(new PartnerNetworkRecordConnection(
                    ConnectionId = networkId2,
                    LocalRecordId = keyLead.Id,
                    SendClosedTasks = true,
                    SendOpenTasks = true,
                    SendEmails = false
                ));
              }
          }

          if(!localProductInterestExabloxLeads.isEmpty()){
              for (Lead keyLead : localProductInterestExabloxLeads) {
                  leadConnections.add(new PartnerNetworkRecordConnection(
                      ConnectionId = networkId1,
                      LocalRecordId = keyLead.Id,
                      SendClosedTasks = true,
                      SendOpenTasks = true,
                      SendEmails = false
                ));
            }
        }
        if (!leadConnections.isEmpty() ) {
            try{
                insert leadConnections;
            }
            catch(DmlException e) {
                // @Developer : Add Error Handling Logic Here.
            }
        }
  }
}