mdapi/objects/NFRCallout__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EncodedAuth__c</fullName>
        <label>EncodedAuth</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassPhrase__c</fullName>
        <label>PassPhrase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NFR Key Callout</label>
</CustomObject>

mdapi/classes/NFRKeyAutomatedCreationTest.cls
@isTest
private class NFRKeyAutomatedCreationTest {

	@isTest static void test_method_one() {
		account a = new account(name = 'AccountTest');
		insert a;
		NFRCallout__c n = new NFRCallout__c(Endpoint__c = 'string', Username__c = 'string', EncodedAuth__c = 'string', PassPhrase__c = 'string');
		insert n;
		list<string> thisList = new list<string>();
		thisList.add(a.id+';English');
		NFRKeyAutomatedCreation.createNewKeys(thisList);
	}
}