mdapi/objects/NFRCallout__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EncodedAuth__c</fullName>
        <label>EncodedAuth</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassPhrase__c</fullName>
        <label>PassPhrase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NFR Key Callout</label>
</CustomObject>

mdapi/classes/LicenseManagerControllerTest.cls
@isTest
private class LicenseManagerControllerTest {

	@isTest static void test_method_one() {
		account a = new account(name = 'AccountTest');
		insert a;
		NFRCallout__c n = new NFRCallout__c(Endpoint__c = 'string', Username__c = 'string', EncodedAuth__c = 'string', PassPhrase__c = 'string');
		insert n;
		Test.setCurrentPageReference(new PageReference('Page.LicenseManager'));
		licenseManagerController lmc = new licenseManagerController();
		System.currentPageReference().getParameters().put('id', a.id);
		lmc.gopage();
		lmc.issueLicenses();
		lmc.addToRequest();
		lmc.confirmRequest();
		lmc.gopage();
		lmc.modifyLicenses();
		lmc.als[0].edit__c = true;
		lmc.extend();
		lmc.als[0].edit__c = true;
		lmc.replace();
		lmc.als[0].edit__c = true;
		lmc.terminate();
		lmc.returnToAccount();
	}
}